{"website": "newbelgium.com", "picture": "https://cdn.beeradvocate.com/im/beers/607.jpg", "style": "American Amber / Red Ale", "name": "Fat Tire Amber Ale", "ba_ratings": "8,608", "city": "Colorado", "country": "United States", "producer": "New Belgium Brewing", "ba_score": "82", "alcohol": " 5.20%\n\t\t"}
{"website": "highlandbrewing.com", "picture": "https://cdn.beeradvocate.com/im/beers/2526.jpg", "style": "American Amber / Red Ale", "name": "Highland Gaelic Ale", "ba_ratings": "1,467", "city": "North Carolina", "country": "United States", "producer": "Highland Brewing", "ba_score": "86", "alcohol": " 5.80%\n\t\t"}
{"website": "ballastpoint.com", "picture": "https://cdn.beeradvocate.com/im/beers/691.jpg", "style": "American Amber / Red Ale", "name": "California Amber", "ba_ratings": "1,431", "city": "California", "country": "United States", "producer": "Ballast Point Brewing Company", "ba_score": "86", "alcohol": " 5.50%\n\t\t"}
{"website": "averybrewing.com", "picture": "https://cdn.beeradvocate.com/im/beers/1490.jpg", "style": "American Amber / Red Ale", "name": "Hog Heaven: Imperial Red IPA", "ba_ratings": "2,069", "city": "Colorado", "country": "United States", "producer": "Avery Brewing Company", "ba_score": "89", "alcohol": " 9.20%\n\t\t"}
{"website": "cigarcitybrewing.com", "picture": "https://cdn.beeradvocate.com/im/beers/61877.jpg", "style": "American Amber / Red Ale", "name": "Tocobaga Red Ale", "ba_ratings": "1,420", "city": "Florida", "country": "United States", "producer": "Cigar City Brewing", "ba_score": "92", "alcohol": " 7.40%\n\t\t"}
{"website": "northcoastbrewing.com", "picture": "https://cdn.beeradvocate.com/im/beers/410.jpg", "style": "American Amber / Red Ale", "name": "Ruedrich's Red Seal Ale", "ba_ratings": "2,069", "city": "California", "country": "United States", "producer": "North Coast Brewing Co.", "ba_score": "88", "alcohol": " 5.40%\n\t\t"}
{"website": "avbc.com", "picture": "https://cdn.beeradvocate.com/im/beers/623.jpg", "style": "American Amber / Red Ale", "name": "Boont Amber Ale", "ba_ratings": "1,564", "city": "California", "country": "United States", "producer": "Anderson Valley Brewing Company", "ba_score": "86", "alcohol": " 5.80%\n\t\t"}
{"website": "rogue.com", "picture": "https://cdn.beeradvocate.com/im/beers/363.jpg", "style": "American Amber / Red Ale", "name": "American Amber Ale", "ba_ratings": "1,444", "city": "Oregon", "country": "United States", "producer": "Rogue Ales", "ba_score": "87", "alcohol": " 5.30%\n\t\t"}
{"website": "mainebeercompany.com", "picture": "https://cdn.beeradvocate.com/im/beers/54522.jpg", "style": "American Amber / Red Ale", "name": "Zoe", "ba_ratings": "2,465", "city": "Maine", "country": "United States", "producer": "Maine Beer Company", "ba_score": "93", "alcohol": " 7.20%\n\t\t"}
{"website": "greatlakesbrewing.com", "picture": "https://cdn.beeradvocate.com/im/beers/1792.jpg", "style": "American Amber / Red Ale", "name": "Great Lakes Nosferatu", "ba_ratings": "2,606", "city": "Ohio", "country": "United States", "producer": "Great Lakes Brewing Co.", "ba_score": "91", "alcohol": " 8.00%\n\t\t"}
{"website": "lagunitas.com", "picture": "https://cdn.beeradvocate.com/im/beers/3711.jpg", "style": "American Amber / Red Ale", "name": "Censored", "ba_ratings": "2,721", "city": "California", "country": "United States", "producer": "Lagunitas Brewing Company", "ba_score": "85", "alcohol": " 6.75%\n\t\t"}
{"website": "sierranevada.com", "picture": "https://cdn.beeradvocate.com/im/beers/98495.jpg", "style": "American Amber / Red Ale", "name": "Flipside Red IPA", "ba_ratings": "2,858", "city": "California", "country": "United States", "producer": "Sierra Nevada Brewing Co.", "ba_score": "86", "alcohol": " 6.20%\n\t\t"}
{"website": "alesmith.com", "picture": "https://cdn.beeradvocate.com/im/beers/10387.jpg", "style": "American Amber / Red Ale", "name": "AleSmith Evil Dead Red", "ba_ratings": "547", "city": "California", "country": "United States", "producer": "AleSmith Brewing Company", "ba_score": "91", "alcohol": " 6.66%\n\t\t"}
{"website": "coronadobrewing.com", "picture": "https://cdn.beeradvocate.com/im/beers/14236.jpg", "style": "American Amber / Red Ale", "name": "Mermaid's Red Ale", "ba_ratings": "550", "city": "California", "country": "United States", "producer": "Coronado Brewing Company", "ba_score": "82", "alcohol": " 5.70%\n\t\t"}
{"website": "bearrepublic.com", "picture": "https://cdn.beeradvocate.com/im/beers/1655.jpg", "style": "American Amber / Red Ale", "name": "Red Rocket Ale", "ba_ratings": "2,602", "city": "California", "country": "United States", "producer": "Bear Republic Brewing Co.", "ba_score": "91", "alcohol": " 6.80%\n\t\t"}
{"website": "rogue.com", "picture": "https://cdn.beeradvocate.com/im/beers/1173.jpg", "style": "American Amber / Red Ale", "name": "Santa's Private Reserve Ale", "ba_ratings": "2,338", "city": "Oregon", "country": "United States", "producer": "Rogue Ales", "ba_score": "85", "alcohol": " 5.30%\n\t\t"}
{"website": "lagunitas.com", "picture": "https://cdn.beeradvocate.com/im/beers/35397.jpg", "style": "American Amber / Red Ale", "name": "Lagunitas Lucky 13 Mondo Large Red Ale", "ba_ratings": "2,650", "city": "California", "country": "United States", "producer": "Lagunitas Brewing Company", "ba_score": "91", "alcohol": " 8.80%\n\t\t"}
{"website": "troegs.com", "picture": "https://cdn.beeradvocate.com/im/beers/6322.jpg", "style": "American Amber / Red Ale", "name": "Tr\u00f6egs Hopback Amber Ale", "ba_ratings": "3,079", "city": "Pennsylvania", "country": "United States", "producer": "Tr\u00f6egs Brewing Company", "ba_score": "90", "alcohol": " 6.00%\n\t\t"}
{"website": "weyerbacher.com", "picture": "https://cdn.beeradvocate.com/im/placeholder-beer.jpg", "style": "American Amber / Red Ale", "name": "AutumnFest", "ba_ratings": "561", "city": "Pennsylvania", "country": "United States", "producer": "Weyerbacher Brewing Co.", "ba_score": "81", "alcohol": " 5.40%\n\t\t"}
{"website": "terrapinbeer.com", "picture": "https://cdn.beeradvocate.com/im/beers/45779.jpg", "style": "American Amber / Red Ale", "name": "Terrapin Oaked Big Hoppy Monster", "ba_ratings": "564", "city": "Georgia", "country": "United States", "producer": "Terrapin Beer Company", "ba_score": "87", "alcohol": " 10.30%\n\t\t"}
{"website": "humboldtbrewingco.com", "picture": "https://cdn.beeradvocate.com/im/beers/1663.jpg", "style": "American Amber / Red Ale", "name": "Red Nectar", "ba_ratings": "587", "city": "California", "country": "United States", "producer": "Humboldt Brewing Co.", "ba_score": "83", "alcohol": " 5.40%\n\t\t"}
{"website": "21st-amendment.com", "picture": "https://cdn.beeradvocate.com/im/beers/185213.jpg", "style": "American Amber / Red Ale", "name": "Toaster Pastry", "ba_ratings": "614", "city": "California", "country": "United States", "producer": "21st Amendment Brewery", "ba_score": "89", "alcohol": " 7.60%\n\t\t"}
{"website": "bridgeportbrew.com", "picture": "https://cdn.beeradvocate.com/im/beers/64798.jpg", "style": "American Amber / Red Ale", "name": "Kingpin Double Red Ale", "ba_ratings": "558", "city": "Oregon", "country": "United States", "producer": "BridgePort Brewing Co. / Brewpub", "ba_score": "80", "alcohol": " 7.50%\n\t\t"}
{"website": "portbrewing.com", "picture": "https://cdn.beeradvocate.com/im/beers/41421.jpg", "style": "American Amber / Red Ale", "name": "Shark Attack Double Red Ale", "ba_ratings": "774", "city": "California", "country": "United States", "producer": "Port Brewing", "ba_score": "87", "alcohol": " 9.00%\n\t\t"}
{"website": "odells.com", "picture": "https://cdn.beeradvocate.com/im/beers/47589.jpg", "style": "American Amber / Red Ale", "name": "Runoff Red IPA", "ba_ratings": "791", "city": "Colorado", "country": "United States", "producer": "Odell Brewing Company", "ba_score": "90", "alcohol": " 6.50%\n\t\t"}
{"website": "aleasylum.com", "picture": "https://cdn.beeradvocate.com/im/beers/31117.jpg", "style": "American Amber / Red Ale", "name": "Ambergeddon", "ba_ratings": "587", "city": "Wisconsin", "country": "United States", "producer": "Ale Asylum", "ba_score": "89", "alcohol": " 6.80%\n\t\t"}
{"website": "newbelgium.com", "picture": "https://cdn.beeradvocate.com/im/beers/83434.jpg", "style": "American Amber / Red Ale", "name": "Red Hoptober", "ba_ratings": "810", "city": "Colorado", "country": "United States", "producer": "New Belgium Brewing", "ba_score": "86", "alcohol": " 6.00%\n\t\t"}
{"website": "revbrew.com", "picture": "https://cdn.beeradvocate.com/im/beers/64036.jpg", "style": "American Amber / Red Ale", "name": "Fistmas", "ba_ratings": "621", "city": "Illinois", "country": "United States", "producer": "Revolution Brewing", "ba_score": "86", "alcohol": " 6.10%\n\t\t"}
{"website": "switchbackvt.com", "picture": "https://cdn.beeradvocate.com/im/beers/11960.jpg", "style": "American Amber / Red Ale", "name": "Switchback Ale", "ba_ratings": "834", "city": "Vermont", "country": "United States", "producer": "Switchback Brewing Company", "ba_score": "81", "alcohol": " 5.00%\n\t\t"}
{"website": "alesmith.com", "picture": "https://cdn.beeradvocate.com/im/beers/28312.jpg", "style": "American Amber / Red Ale", "name": "AleSmith My Bloody Valentine", "ba_ratings": "672", "city": "California", "country": "United States", "producer": "AleSmith Brewing Company", "ba_score": "89", "alcohol": " 6.66%\n\t\t"}
{"website": "brewdog.com", "picture": "https://cdn.beeradvocate.com/im/beers/55191.jpg", "style": "American Amber / Red Ale", "name": "5AM Saint", "ba_ratings": "836", "city": "Scotland", "country": "United Kingdom", "producer": "BrewDog", "ba_score": "86", "alcohol": " 5.00%\n\t\t"}
{"website": "pdubs.net", "picture": "https://cdn.beeradvocate.com/im/beers/81742.jpg", "style": "American Amber / Red Ale", "name": "Blood Of The Unicorn", "ba_ratings": "649", "city": "Illinois", "country": "United States", "producer": "Pipeworks Brewing Company", "ba_score": "89", "alcohol": " 6.50%\n\t\t"}
{"website": "rogue.com", "picture": "https://cdn.beeradvocate.com/im/beers/51071.jpg", "style": "American Amber / Red Ale", "name": "Captain Sig's Northwestern Ale", "ba_ratings": "804", "city": "Oregon", "country": "United States", "producer": "Rogue Ales", "ba_score": "85", "alcohol": " 6.20%\n\t\t"}
{"website": "alesmith.com", "picture": "https://cdn.beeradvocate.com/im/beers/47647.jpg", "style": "American Amber / Red Ale", "name": "Double Red India Pale Ale", "ba_ratings": "886", "city": "California", "country": "United States", "producer": "AleSmith Brewing Company", "ba_score": "91", "alcohol": " 8.50%\n\t\t"}
{"website": "lakefrontbrewery.com", "picture": "https://cdn.beeradvocate.com/im/beers/56386.jpg", "style": "American Amber / Red Ale", "name": "Fixed Gear", "ba_ratings": "926", "city": "Wisconsin", "country": "United States", "producer": "Lakefront Brewery, Inc.", "ba_score": "85", "alcohol": " 6.80%\n\t\t"}
{"website": "ballastpoint.com", "picture": "https://cdn.beeradvocate.com/im/beers/7306.jpg", "style": "American Amber / Red Ale", "name": "Tongue Buckler - Imperial Red Ale", "ba_ratings": "938", "city": "California", "country": "United States", "producer": "Ballast Point Brewing Company", "ba_score": "87", "alcohol": " 10.00%\n\t\t"}
{"website": "mainebeercompany.com", "picture": "https://cdn.beeradvocate.com/im/beers/103142.jpg", "style": "American Amber / Red Ale", "name": "Red Wheelbarrow", "ba_ratings": "961", "city": "Maine", "country": "United States", "producer": "Maine Beer Company", "ba_score": "91", "alcohol": " 7.00%\n\t\t"}
{"website": "calderabrewing.com", "picture": "https://cdn.beeradvocate.com/im/beers/10785.jpg", "style": "American Amber / Red Ale", "name": "Ashland Amber", "ba_ratings": "276", "city": "Oregon", "country": "United States", "producer": "Caldera Brewing Company", "ba_score": "84", "alcohol": " 5.40%\n\t\t"}
{"website": "duckrabbitbrewery.com", "picture": "https://cdn.beeradvocate.com/im/beers/19976.jpg", "style": "American Amber / Red Ale", "name": "Duck-Rabbit Amber Ale", "ba_ratings": "524", "city": "North Carolina", "country": "United States", "producer": "The Duck-Rabbit Craft Brewery", "ba_score": "78", "alcohol": " 5.50%\n\t\t"}
{"website": "mendobrew.com", "picture": "https://cdn.beeradvocate.com/im/beers/631.jpg", "style": "American Amber / Red Ale", "name": "Red Tail Ale", "ba_ratings": "961", "city": "", "country": "United States", "producer": "Mendocino Brewing Company", "ba_score": "79", "alcohol": "\n\t\t"}
{"website": "mayflowerbrewing.com", "picture": "https://cdn.beeradvocate.com/im/beers/67109.jpg", "style": "American Amber / Red Ale", "name": "Mayflower Spring Hop", "ba_ratings": "278", "city": "Massachusetts", "country": "United States", "producer": "Mayflower Brewing Company", "ba_score": "90", "alcohol": " 5.30%\n\t\t"}
{"website": "gooseisland.com", "picture": "https://cdn.beeradvocate.com/im/beers/21024.jpg", "style": "American Amber / Red Ale", "name": "Goose Autumn Ale", "ba_ratings": "279", "city": "Illinois", "country": "United States", "producer": "Goose Island Beer Co.", "ba_score": "84", "alcohol": " 6.70%\n\t\t"}
{"website": "jackieos.com", "picture": "https://cdn.beeradvocate.com/im/beers/58983.jpg", "style": "American Amber / Red Ale", "name": "Firefly Amber Ale", "ba_ratings": "284", "city": "Ohio", "country": "United States", "producer": "Jackie O's Pub & Brewery", "ba_score": "80", "alcohol": " 4.50%\n\t\t"}
{"website": "rogue.com", "picture": "https://cdn.beeradvocate.com/im/beers/40187.jpg", "style": "American Amber / Red Ale", "name": "XS Imperial Red", "ba_ratings": "291", "city": "Oregon", "country": "United States", "producer": "Rogue Ales", "ba_score": "85", "alcohol": " 9.00%\n\t\t"}
{"website": "elysianbrewing.com", "picture": "https://cdn.beeradvocate.com/im/beers/59248.jpg", "style": "American Amber / Red Ale", "name": "The Men's Room Ale", "ba_ratings": "296", "city": "Washington", "country": "United States", "producer": "Elysian Brewing Company", "ba_score": "82", "alcohol": " 5.60%\n\t\t"}
{"website": "belfastbaybrewing.com", "picture": "https://cdn.beeradvocate.com/im/beers/2532.jpg", "style": "American Amber / Red Ale", "name": "Lobster Ale", "ba_ratings": "308", "city": "Maine", "country": "United States", "producer": "Belfast Bay Brewing Co.", "ba_score": "80", "alcohol": " 5.00%\n\t\t"}
{"website": "ofallonbrewery.com", "picture": "https://cdn.beeradvocate.com/im/beers/56887.jpg", "style": "American Amber / Red Ale", "name": "Hemp Hop Rye", "ba_ratings": "329", "city": "Missouri", "country": "United States", "producer": "O'Fallon Brewery", "ba_score": "81", "alcohol": " 5.50%\n\t\t"}
{"website": "centralwaters.com", "picture": "https://cdn.beeradvocate.com/im/beers/3997.jpg", "style": "American Amber / Red Ale", "name": "Ouisconsing Red Ale", "ba_ratings": "277", "city": "Wisconsin", "country": "United States", "producer": "Central Waters Brewing Co.", "ba_score": "81", "alcohol": " 4.80%\n\t\t"}
{"website": "skabrewing.com", "picture": "https://cdn.beeradvocate.com/im/beers/3148.jpg", "style": "American Amber / Red Ale", "name": "Pinstripe Red Ale", "ba_ratings": "332", "city": "Colorado", "country": "United States", "producer": "Ska Brewing Co.", "ba_score": "80", "alcohol": " 5.15%\n\t\t"}
{"website": "newportstorm.com", "picture": "https://cdn.beeradvocate.com/im/beers/3153.jpg", "style": "American Amber / Red Ale", "name": "Newport Storm Hurricane Amber Ale", "ba_ratings": "333", "city": "Rhode Island", "country": "United States", "producer": "Coastal Extreme Brewing Co.", "ba_score": "75", "alcohol": " 5.20%\n\t\t"}
{"website": "coors.com", "picture": "https://cdn.beeradvocate.com/im/beers/40528.jpg", "style": "American Amber / Red Ale", "name": "Blue Moon Rising Moon Spring Ale", "ba_ratings": "350", "city": "Colorado", "country": "United States", "producer": "Coors Brewing Company", "ba_score": "71", "alcohol": " 5.40%\n\t\t"}
{"website": "newbelgium.com", "picture": "https://cdn.beeradvocate.com/im/beers/217618.jpg", "style": "American Amber / Red Ale", "name": "Fat Tire And Friends Fat Hoppy Ale", "ba_ratings": "360", "city": "Colorado", "country": "United States", "producer": "New Belgium Brewing", "ba_score": "89", "alcohol": " 6.00%\n\t\t"}
{"website": "nattygreenes.com", "picture": "https://cdn.beeradvocate.com/im/beers/19165.jpg", "style": "American Amber / Red Ale", "name": "Buckshot Amber Ale", "ba_ratings": "373", "city": "North Carolina", "country": "United States", "producer": "Natty Greene's Pub & Brewing Co.", "ba_score": "79", "alcohol": " 4.90%\n\t\t"}
{"website": "twobrothersbrewing.com", "picture": "https://cdn.beeradvocate.com/im/beers/87343.jpg", "style": "American Amber / Red Ale", "name": "Revelry", "ba_ratings": "368", "city": "Illinois", "country": "United States", "producer": "Two Brothers Brewing Company", "ba_score": "90", "alcohol": " 9.50%\n\t\t"}
{"website": "redhook.com", "picture": "https://cdn.beeradvocate.com/im/beers/28712.jpg", "style": "American Amber / Red Ale", "name": "Redhook Late Harvest Autumn Ale", "ba_ratings": "294", "city": "New Hampshire", "country": "United States", "producer": "Redhook Ale Brewery", "ba_score": "79", "alcohol": " 5.90%\n\t\t"}
{"website": "deschutesbrewery.com", "picture": "https://cdn.beeradvocate.com/im/beers/40291.jpg", "style": "American Amber / Red Ale", "name": "Green Lakes Organic Ale", "ba_ratings": "351", "city": "Oregon", "country": "United States", "producer": "Deschutes Brewery", "ba_score": "85", "alcohol": " 5.20%\n\t\t"}
{"website": "samueladams.com", "picture": "https://cdn.beeradvocate.com/im/beers/183489.jpg", "style": "American Amber / Red Ale", "name": "Hoppy Red", "ba_ratings": "382", "city": "Massachusetts", "country": "United States", "producer": "Boston Beer Company (Samuel Adams)", "ba_score": "83", "alcohol": " 5.70%\n\t\t"}
{"website": "lostnationbrewing.com", "picture": "https://cdn.beeradvocate.com/im/placeholder-beer.jpg", "style": "American Amber / Red Ale", "name": "Rustic Ale", "ba_ratings": "176", "city": "Vermont", "country": "United States", "producer": "Lost Nation Brewing", "ba_score": "84", "alcohol": " 5.40%\n\t\t"}
{"website": "independencebrewing.com", "picture": "https://cdn.beeradvocate.com/im/beers/34704.jpg", "style": "American Amber / Red Ale", "name": "Austin Amber Ale", "ba_ratings": "210", "city": "Texas", "country": "United States", "producer": "Independence Brewing Co.", "ba_score": "77", "alcohol": " 4.80%\n\t\t"}
{"website": "rushriverbeer.com", "picture": "https://cdn.beeradvocate.com/im/beers/18738.jpg", "style": "American Amber / Red Ale", "name": "The Unforgiven Amber Ale", "ba_ratings": "175", "city": "Wisconsin", "country": "United States", "producer": "Rush River Brewing Company", "ba_score": "84", "alcohol": " 5.80%\n\t\t"}
{"website": "cambridgebrewingcompany.com", "picture": "https://cdn.beeradvocate.com/im/beers/13816.jpg", "style": "American Amber / Red Ale", "name": "Red God", "ba_ratings": "177", "city": "Massachusetts", "country": "United States", "producer": "Cambridge Brewing Company", "ba_score": "90", "alcohol": " 9.00%\n\t\t"}
{"website": "grandtetonbrewing.com", "picture": "https://cdn.beeradvocate.com/im/beers/4998.jpg", "style": "American Amber / Red Ale", "name": "Amber Ale", "ba_ratings": "175", "city": "Idaho", "country": "United States", "producer": "Grand Teton Brewing Co.", "ba_score": "80", "alcohol": " 5.30%\n\t\t"}
{"website": "blackdogales.com", "picture": "https://cdn.beeradvocate.com/im/beers/36731.jpg", "style": "American Amber / Red Ale", "name": "Black Dog Ale", "ba_ratings": "179", "city": "California", "country": "United States", "producer": "Spanish Peaks Brewing Co.", "ba_score": "80", "alcohol": " 5.20%\n\t\t"}
{"website": "fultonbeer.com", "picture": "https://cdn.beeradvocate.com/im/beers/63753.jpg", "style": "American Amber / Red Ale", "name": "The Libertine", "ba_ratings": "180", "city": "Minnesota", "country": "United States", "producer": "Fulton Beer", "ba_score": "87", "alcohol": " 8.50%\n\t\t"}
{"website": "14thstarbrewing.com", "picture": "https://cdn.beeradvocate.com/im/beers/97134.jpg", "style": "American Amber / Red Ale", "name": "Valor Ale", "ba_ratings": "180", "city": "Vermont", "country": "United States", "producer": "14th Star Brewing Co.", "ba_score": "84", "alcohol": " 5.40%\n\t\t"}
{"website": "mountaintownbrew.com", "picture": "https://cdn.beeradvocate.com/im/beers/56940.jpg", "style": "American Amber / Red Ale", "name": "Train Wreck Ale", "ba_ratings": "183", "city": "Michigan", "country": "United States", "producer": "Mountain Town Brewing Co.", "ba_score": "80", "alcohol": " 8.20%\n\t\t"}
{"website": "portbrewing.com", "picture": "https://cdn.beeradvocate.com/im/beers/30656.jpg", "style": "American Amber / Red Ale", "name": "Shark Bite Red Ale", "ba_ratings": "186", "city": "California", "country": "United States", "producer": "Port Brewing", "ba_score": "85", "alcohol": " 6.00%\n\t\t"}
{"website": "flyingfish.com", "picture": "https://cdn.beeradvocate.com/im/beers/66113.jpg", "style": "American Amber / Red Ale", "name": "Exit 9", "ba_ratings": "182", "city": "New Jersey", "country": "United States", "producer": "Flying Fish Brewing Company", "ba_score": "89", "alcohol": " 9.00%\n\t\t"}
{"website": "coopaleworks.com", "picture": "https://cdn.beeradvocate.com/im/beers/48720.jpg", "style": "American Amber / Red Ale", "name": "Native Amber", "ba_ratings": "187", "city": "Oklahoma", "country": "United States", "producer": "Coop Ale Works", "ba_score": "88", "alcohol": " 6.10%\n\t\t"}
{"website": null, "picture": "https://cdn.beeradvocate.com/im/beers/5655.jpg", "style": "American Amber / Red Ale", "name": "Jumping Cow Amber Ale", "ba_ratings": "186", "city": "California", "country": "United States", "producer": "Steinhaus Brewing Co.", "ba_score": "75", "alcohol": " 5.50%\n\t\t"}
{"website": "flyingbisonbrewing.com", "picture": "https://cdn.beeradvocate.com/im/beers/47193.jpg", "style": "American Amber / Red Ale", "name": "Rusty Chain", "ba_ratings": "188", "city": "New York", "country": "United States", "producer": "Flying Bison Brewing Company", "ba_score": "78", "alcohol": " 5.00%\n\t\t"}
{"website": "madtreebrewing.com", "picture": "https://cdn.beeradvocate.com/im/beers/92730.jpg", "style": "American Amber / Red Ale", "name": "Happy Amber", "ba_ratings": "184", "city": "Ohio", "country": "United States", "producer": "MadTree Brewing", "ba_score": "87", "alcohol": " 6.00%\n\t\t"}
{"website": "soprobrewing.com", "picture": "https://cdn.beeradvocate.com/im/beers/108380.jpg", "style": "American Amber / Red Ale", "name": "Mississippi Fire Ant", "ba_ratings": "132", "city": "Mississippi", "country": "United States", "producer": "Southern Prohibition Brewing", "ba_score": "86", "alcohol": " 8.00%\n\t\t"}
{"website": "keweenawbrewing.com", "picture": "https://cdn.beeradvocate.com/im/beers/30693.jpg", "style": "American Amber / Red Ale", "name": "Red Jacket Amber Ale", "ba_ratings": "135", "city": "Michigan", "country": "United States", "producer": "Keweenaw Brewing Company", "ba_score": "80", "alcohol": " 5.10%\n\t\t"}
{"website": null, "picture": "https://cdn.beeradvocate.com/im/beers/48556.jpg", "style": "American Amber / Red Ale", "name": "Kirkland Signature Amber Ale", "ba_ratings": "190", "city": "Washington", "country": "United States", "producer": "Kirkland Signature / Costco Wholesale Corporation", "ba_score": "75", "alcohol": " 5.70%\n\t\t"}
{"website": "kernriverbrewing.com", "picture": "https://cdn.beeradvocate.com/im/beers/79810.jpg", "style": "American Amber / Red Ale", "name": "6th Anniversary Ale (Dirty Hippie Imperial Red Ale)", "ba_ratings": "136", "city": "California", "country": "United States", "producer": "Kern River Brewing Company", "ba_score": "91", "alcohol": " 8.00%\n\t\t"}
{"website": "opaopasteakhousebrewery.com", "picture": "https://cdn.beeradvocate.com/im/beers/20336.jpg", "style": "American Amber / Red Ale", "name": "Red Rock Amber Ale", "ba_ratings": "135", "city": "Massachusetts", "country": "United States", "producer": "OPA-OPA Steakhouse & Brewery", "ba_score": "83", "alcohol": " 6.00%\n\t\t"}
{"website": "elementbeer.com", "picture": "https://cdn.beeradvocate.com/im/beers/56425.jpg", "style": "American Amber / Red Ale", "name": "Red Giant", "ba_ratings": "132", "city": "Massachusetts", "country": "United States", "producer": "Element Brewing Company", "ba_score": "88", "alcohol": " 8.25%\n\t\t"}
{"website": "magichat.net", "picture": "https://cdn.beeradvocate.com/im/beers/97391.jpg", "style": "American Amber / Red Ale", "name": "Deveiled", "ba_ratings": "135", "city": "Vermont", "country": "United States", "producer": "Magic Hat Brewing Company", "ba_score": "78", "alcohol": " 5.20%\n\t\t"}
{"website": "boneyardbeer.com", "picture": "https://cdn.beeradvocate.com/im/beers/62777.jpg", "style": "American Amber / Red Ale", "name": "Diablo Rojo", "ba_ratings": "134", "city": "Oregon", "country": "United States", "producer": "Boneyard Beer Company", "ba_score": "83", "alcohol": " 7.00%\n\t\t"}
{"website": "epicbrewing.com", "picture": "https://cdn.beeradvocate.com/im/beers/60873.jpg", "style": "American Amber / Red Ale", "name": "Imperial Red Ale", "ba_ratings": "136", "city": "Utah", "country": "United States", "producer": "Epic Brewing Company", "ba_score": "85", "alcohol": " 7.70%\n\t\t"}
{"website": "mexicalibeer.com", "picture": "https://cdn.beeradvocate.com/im/beers/108604.jpg", "style": "American Amber / Red Ale", "name": "Day Of The Dead Beer (Cerveza De Los Muertos) Death Becomes You", "ba_ratings": "137", "city": "", "country": "Mexico", "producer": "Cerveceria Mexicana S.A. De C.V.", "ba_score": "77", "alcohol": "\n\t\t"}
{"website": "prismbeer.com", "picture": "https://cdn.beeradvocate.com/im/placeholder-beer.jpg", "style": "American Amber / Red Ale", "name": "Bitto Honey", "ba_ratings": "137", "city": "Pennsylvania", "country": "United States", "producer": "Prism Brewing Company", "ba_score": "81", "alcohol": " 6.50%\n\t\t"}
{"website": "goodbeer.com", "picture": "https://cdn.beeradvocate.com/im/beers/59589.jpg", "style": "American Amber / Red Ale", "name": "Betrayal Imperial Red", "ba_ratings": "140", "city": "California", "country": "United States", "producer": "Speakeasy Ales & Lagers", "ba_score": "86", "alcohol": " 8.20%\n\t\t"}
{"website": "peacetreebrewing.com", "picture": "https://cdn.beeradvocate.com/im/beers/58495.jpg", "style": "American Amber / Red Ale", "name": "Red Rambler Ale", "ba_ratings": "137", "city": "Iowa", "country": "United States", "producer": "Peace Tree Brewing Co.", "ba_score": "79", "alcohol": " 5.80%\n\t\t"}
{"website": "eelriverbrewing.com", "picture": "https://cdn.beeradvocate.com/im/placeholder-beer.jpg", "style": "American Amber / Red Ale", "name": "Amber Ale", "ba_ratings": "142", "city": "California", "country": "United States", "producer": "Eel River Brewing Co.", "ba_score": "76", "alcohol": " 4.75%\n\t\t"}
{"website": "wickedweedbrewing.com", "picture": "https://cdn.beeradvocate.com/im/beers/100232.jpg", "style": "American Amber / Red Ale", "name": "Tyrant Double Red", "ba_ratings": "136", "city": "North Carolina", "country": "United States", "producer": "Wicked Weed Brewing", "ba_score": "90", "alcohol": " 8.50%\n\t\t"}
{"website": "griffinclawbrewingcompany.com", "picture": "https://cdn.beeradvocate.com/im/beers/107557.jpg", "style": "American Amber / Red Ale", "name": "El Rojo Red Ale", "ba_ratings": "141", "city": "Michigan", "country": "United States", "producer": "Griffin Claw Brewing Company", "ba_score": "84", "alcohol": " 6.50%\n\t\t"}
{"website": "sleeman.com", "picture": "https://cdn.beeradvocate.com/im/beers/27398.jpg", "style": "American Amber / Red Ale", "name": "Sleeman Original Dark (50*)", "ba_ratings": "102", "city": "Ontario", "country": "Canada", "producer": "Sleeman Breweries Ltd.", "ba_score": "73", "alcohol": " 5.50%\n\t\t"}
{"website": "sprecherbrewery.com", "picture": "https://cdn.beeradvocate.com/im/beers/34780.jpg", "style": "American Amber / Red Ale", "name": "Shakparo (Fire-Brewed African Style-Ale)", "ba_ratings": "103", "city": "Wisconsin", "country": "United States", "producer": "Sprecher Brewing Company", "ba_score": "75", "alcohol": " 5.70%\n\t\t"}
{"website": "tightheadbrewing.com", "picture": "https://cdn.beeradvocate.com/im/beers/75083.jpg", "style": "American Amber / Red Ale", "name": "Scarlet Fire", "ba_ratings": "103", "city": "Illinois", "country": "United States", "producer": "Tighthead Brewing Company", "ba_score": "83", "alcohol": " 5.60%\n\t\t"}
{"website": "perrinbrewing.com", "picture": "https://cdn.beeradvocate.com/im/placeholder-beer.jpg", "style": "American Amber / Red Ale", "name": "Kona Brown", "ba_ratings": "103", "city": "Michigan", "country": "United States", "producer": "Perrin Brewery", "ba_score": "88", "alcohol": " 5.50%\n\t\t"}
{"website": "creaturecomfortsbeer.com", "picture": "https://cdn.beeradvocate.com/im/placeholder-beer.jpg", "style": "American Amber / Red Ale", "name": "Reclaimed Rye", "ba_ratings": "104", "city": "Georgia", "country": "United States", "producer": "Creature Comforts", "ba_score": "91", "alcohol": " 5.50%\n\t\t"}
{"website": "ottospubandbrewery.com", "picture": "https://cdn.beeradvocate.com/im/beers/7970.jpg", "style": "American Amber / Red Ale", "name": "Red Mo Ale", "ba_ratings": "125", "city": "Pennsylvania", "country": "United States", "producer": "Otto's Pub and Brewery", "ba_score": "84", "alcohol": " 5.00%\n\t\t"}
{"website": "bigmuddybrewing.com", "picture": "https://cdn.beeradvocate.com/im/beers/56542.jpg", "style": "American Amber / Red Ale", "name": "Saluki Dunkeldog", "ba_ratings": "105", "city": "Illinois", "country": "United States", "producer": "Big Muddy Brewing", "ba_score": "80", "alcohol": " 5.40%\n\t\t"}
{"website": null, "picture": "https://cdn.beeradvocate.com/im/beers/325.jpg", "style": "American Amber / Red Ale", "name": "McNeill's Firehouse Amber Ale", "ba_ratings": "105", "city": "Vermont", "country": "United States", "producer": "McNeill's Brewery", "ba_score": "83", "alcohol": " 5.60%\n\t\t"}
{"website": "mcauslan.com", "picture": "https://cdn.beeradvocate.com/im/beers/14795.jpg", "style": "American Amber / Red Ale", "name": "Griffon Red Ale", "ba_ratings": "118", "city": "Quebec", "country": "Canada", "producer": "McAuslan Brewing", "ba_score": "81", "alcohol": " 4.50%\n\t\t"}
{"website": "boreale.com", "picture": "https://cdn.beeradvocate.com/im/beers/6876.jpg", "style": "American Amber / Red Ale", "name": "Bor\u00e9ale Rousse", "ba_ratings": "108", "city": "Quebec", "country": "Canada", "producer": "Brasseurs Du Nord Inc.", "ba_score": "81", "alcohol": " 5.00%\n\t\t"}
{"website": "duclaw.com", "picture": "https://cdn.beeradvocate.com/im/beers/13081.jpg", "style": "American Amber / Red Ale", "name": "Misfit Red", "ba_ratings": "109", "city": "Maryland", "country": "United States", "producer": "DuClaw Brewing Company", "ba_score": "82", "alcohol": " 5.10%\n\t\t"}
{"website": "badweatherbrewery.com", "picture": "https://cdn.beeradvocate.com/im/beers/92069.jpg", "style": "American Amber / Red Ale", "name": "Windvane", "ba_ratings": "111", "city": "Minnesota", "country": "United States", "producer": "Bad Weather Brewing Company", "ba_score": "86", "alcohol": " 6.00%\n\t\t"}
{"website": "1812ale.com", "picture": "https://cdn.beeradvocate.com/im/beers/1885.jpg", "style": "American Amber / Red Ale", "name": "War Of 1812 Ale", "ba_ratings": "111", "city": "New York", "country": "United States", "producer": "Sackets Harbor Brewing Co.", "ba_score": "79", "alcohol": " 5.20%\n\t\t"}
{"website": "magichat.net", "picture": "https://cdn.beeradvocate.com/im/beers/244539.jpg", "style": "American Amber / Red Ale", "name": "Vamplifier", "ba_ratings": "107", "city": "Vermont", "country": "United States", "producer": "Magic Hat Brewing Company", "ba_score": "82", "alcohol": " 5.20%\n\t\t"}
{"website": "bigstormbrewery.com", "picture": "https://cdn.beeradvocate.com/im/beers/102462.jpg", "style": "American Amber / Red Ale", "name": "Wavemaker Amber Ale", "ba_ratings": "113", "city": "Florida", "country": "United States", "producer": "Big Storm Brewing Company", "ba_score": "83", "alcohol": " 4.90%\n\t\t"}
{"website": "evolutioncraftbrewing.com", "picture": "https://cdn.beeradvocate.com/im/beers/115640.jpg", "style": "American Amber / Red Ale", "name": "Exile Red", "ba_ratings": "111", "city": "Maryland", "country": "United States", "producer": "Evolution Craft Brewing Company", "ba_score": "81", "alcohol": " 5.90%\n\t\t"}
{"website": "lakeofbaysbrewing.ca", "picture": "https://cdn.beeradvocate.com/im/beers/69888.jpg", "style": "American Amber / Red Ale", "name": "Spark House Red Ale", "ba_ratings": "105", "city": "Ontario", "country": "Canada", "producer": "Lake of Bays Brewing Company", "ba_score": "82", "alcohol": " 5.00%\n\t\t"}
{"website": "odinbrewing.com", "picture": "https://cdn.beeradvocate.com/im/beers/54973.jpg", "style": "American Amber / Red Ale", "name": "Odin's Gift", "ba_ratings": "115", "city": "Washington", "country": "United States", "producer": "Odin Brewing Company", "ba_score": "83", "alcohol": " 5.40%\n\t\t"}
{"website": "bellsbeer.com", "picture": "https://cdn.beeradvocate.com/im/beers/6383.jpg", "style": "American Amber / Red Ale", "name": "Bell's Deb's Red Ale", "ba_ratings": "116", "city": "Michigan", "country": "United States", "producer": "Bell's Brewery, Inc.", "ba_score": "85", "alcohol": " 6.30%\n\t\t"}
{"website": "3sheepsbrewing.com", "picture": "https://cdn.beeradvocate.com/im/placeholder-beer.jpg", "style": "American Amber / Red Ale", "name": "Rebel Kent", "ba_ratings": "108", "city": "Wisconsin", "country": "United States", "producer": "3 Sheeps Brewing", "ba_score": "81", "alcohol": " 5.00%\n\t\t"}
{"website": "rockbottom.com", "picture": "https://cdn.beeradvocate.com/im/placeholder-beer.jpg", "style": "American Amber / Red Ale", "name": "Rock Bottom Red Ale", "ba_ratings": "116", "city": "", "country": "United States", "producer": "Rock Bottom Restaurant & Brewery", "ba_score": "78", "alcohol": "\n\t\t"}
{"website": "empirebrew.com", "picture": "https://cdn.beeradvocate.com/im/placeholder-beer.jpg", "style": "American Amber / Red Ale", "name": "Empire East Coast Amber", "ba_ratings": "79", "city": "New York", "country": "United States", "producer": "Empire Brewing Company - Brewpub", "ba_score": "81", "alcohol": " 5.60%\n\t\t"}
{"website": "scuttlebuttbrewing.com", "picture": "https://cdn.beeradvocate.com/im/beers/10496.jpg", "style": "American Amber / Red Ale", "name": "Scuttlebutt Amber", "ba_ratings": "113", "city": "Washington", "country": "United States", "producer": "Scuttlebutt Brewing Company", "ba_score": "79", "alcohol": " 5.10%\n\t\t"}
{"website": "kernriverbrewing.com", "picture": "https://cdn.beeradvocate.com/im/beers/35607.jpg", "style": "American Amber / Red Ale", "name": "Sequoia Red", "ba_ratings": "78", "city": "California", "country": "United States", "producer": "Kern River Brewing Company", "ba_score": "83", "alcohol": " 5.20%\n\t\t"}
{"website": "halesbrewery.com", "picture": "https://cdn.beeradvocate.com/im/beers/19974.jpg", "style": "American Amber / Red Ale", "name": "Hale's Red Menace Big Amber", "ba_ratings": "92", "city": "Washington", "country": "United States", "producer": "Hale's Ales Brewery & Pub", "ba_score": "80", "alcohol": " 4.60%\n\t\t"}
{"website": "iron-horse-brewery.com", "picture": "https://cdn.beeradvocate.com/im/beers/66753.jpg", "style": "American Amber / Red Ale", "name": "Double Rainbow Ale", "ba_ratings": "79", "city": "Washington", "country": "United States", "producer": "Iron Horse Brewery", "ba_score": "82", "alcohol": " 7.00%\n\t\t"}
{"website": "oconnorbrewing.com", "picture": "https://cdn.beeradvocate.com/im/beers/59245.jpg", "style": "American Amber / Red Ale", "name": "Red Nun Red Ale", "ba_ratings": "83", "city": "Virginia", "country": "United States", "producer": "O'Connor Brewing Co.", "ba_score": "81", "alcohol": " 5.50%\n\t\t"}
{"website": "mountainstatebrewing.com", "picture": "https://cdn.beeradvocate.com/im/placeholder-beer.jpg", "style": "American Amber / Red Ale", "name": "Almost Heaven Amber Ale", "ba_ratings": "80", "city": "West Virginia", "country": "United States", "producer": "Mountain State Brewing Co.", "ba_score": "84", "alcohol": " 5.20%\n\t\t"}
{"website": "coastbrewing.com", "picture": "https://cdn.beeradvocate.com/im/beers/63811.jpg", "style": "American Amber / Red Ale", "name": "Carnie Fire", "ba_ratings": "79", "city": "South Carolina", "country": "United States", "producer": "COAST Brewing Company", "ba_score": "91", "alcohol": " 5.00%\n\t\t"}
{"website": "rogue.com", "picture": "https://cdn.beeradvocate.com/im/beers/25749.jpg", "style": "American Amber / Red Ale", "name": "Red Fox Amber Ale", "ba_ratings": "80", "city": "Oregon", "country": "United States", "producer": "Rogue Ales", "ba_score": "83", "alcohol": " not listed\n\t\t"}
{"website": "ghostriverbrewing.com", "picture": "https://cdn.beeradvocate.com/im/beers/60669.jpg", "style": "American Amber / Red Ale", "name": "Ghost River Riverbank Red", "ba_ratings": "82", "city": "Tennessee", "country": "United States", "producer": "Ghost River Brewing", "ba_score": "83", "alcohol": " not listed\n\t\t"}
{"website": "grandtetonbrewing.com", "picture": "https://cdn.beeradvocate.com/im/beers/34711.jpg", "style": "American Amber / Red Ale", "name": "Bone Warmer Imperial Amber Ale", "ba_ratings": "79", "city": "Idaho", "country": "United States", "producer": "Grand Teton Brewing Co.", "ba_score": "84", "alcohol": " 8.20%\n\t\t"}
{"website": "flossmoorstation.com", "picture": "https://cdn.beeradvocate.com/im/beers/3102.jpg", "style": "American Amber / Red Ale", "name": "Panama Limited Red Ale", "ba_ratings": "82", "city": "Illinois", "country": "United States", "producer": "Flossmoor Station Restaurant & Brewery", "ba_score": "84", "alcohol": " not listed\n\t\t"}
{"website": "southstreetbrewery.com", "picture": "https://cdn.beeradvocate.com/im/beers/4837.jpg", "style": "American Amber / Red Ale", "name": "Satan's Pony Amber Ale", "ba_ratings": "84", "city": "Virginia", "country": "United States", "producer": "South Street Brewery", "ba_score": "81", "alcohol": " 5.00%\n\t\t"}
{"website": "northloopbrew.co", "picture": "https://cdn.beeradvocate.com/im/beers/90343.jpg", "style": "American Amber / Red Ale", "name": "Duce", "ba_ratings": "82", "city": "Minnesota", "country": "United States", "producer": "North Loop Brew Co", "ba_score": "85", "alcohol": " 7.50%\n\t\t"}
{"website": "mkebrewing.com", "picture": "https://cdn.beeradvocate.com/im/beers/61471.jpg", "style": "American Amber / Red Ale", "name": "Louie's Demise Immort-Ale", "ba_ratings": "82", "city": "Wisconsin", "country": "United States", "producer": "Milwaukee Brewing Company", "ba_score": "81", "alcohol": " 4.80%\n\t\t"}
{"website": "napasmithbrewery.com", "picture": "https://cdn.beeradvocate.com/im/beers/46260.jpg", "style": "American Amber / Red Ale", "name": "Amber Ale", "ba_ratings": "81", "city": "California", "country": "United States", "producer": "Napa Smith Brewery", "ba_score": "80", "alcohol": " 5.75%\n\t\t"}
{"website": "mammothbrewingco.com", "picture": "https://cdn.beeradvocate.com/im/beers/38940.jpg", "style": "American Amber / Red Ale", "name": "Real McCoy Amber Ale", "ba_ratings": "80", "city": "California", "country": "United States", "producer": "Mammoth Brewing Company", "ba_score": "82", "alcohol": " 4.50%\n\t\t"}
{"website": "eltorobrewing.com", "picture": "https://cdn.beeradvocate.com/im/beers/1736.jpg", "style": "American Amber / Red Ale", "name": "El Toro Poppy Jasper", "ba_ratings": "80", "city": "California", "country": "United States", "producer": "El Toro Brewing Co.", "ba_score": "81", "alcohol": " 5.30%\n\t\t"}
{"website": "pizzaport.com", "picture": "https://cdn.beeradvocate.com/im/placeholder-beer.jpg", "style": "American Amber / Red Ale", "name": "Carlsbad Chronic", "ba_ratings": "86", "city": "California", "country": "United States", "producer": "Pizza Port Solana Beach", "ba_score": "81", "alcohol": " 5.80%\n\t\t"}
{"website": "frankenmuthbrewery.com", "picture": "https://cdn.beeradvocate.com/im/beers/105117.jpg", "style": "American Amber / Red Ale", "name": "Frankenmuth Christmas Town Ale", "ba_ratings": "85", "city": "Michigan", "country": "United States", "producer": "Frankenmuth Brewery", "ba_score": "84", "alcohol": " 6.70%\n\t\t"}
{"website": "ruhstallerbeer.com", "picture": "https://cdn.beeradvocate.com/im/beers/77997.jpg", "style": "American Amber / Red Ale", "name": "1881 Sacramento", "ba_ratings": "88", "city": "California", "country": "United States", "producer": "Ruhstaller", "ba_score": "84", "alcohol": " 5.60%\n\t\t"}
{"website": "solemnoathbrewery.com", "picture": "https://cdn.beeradvocate.com/im/placeholder-beer.jpg", "style": "American Amber / Red Ale", "name": "Man Vs. Internet", "ba_ratings": "84", "city": "Illinois", "country": "United States", "producer": "Solemn Oath Brewery", "ba_score": "87", "alcohol": " 9.50%\n\t\t"}
{"website": "kneedeepbrewing.com", "picture": "https://cdn.beeradvocate.com/im/beers/85749.jpg", "style": "American Amber / Red Ale", "name": "McCarthy's Bane", "ba_ratings": "86", "city": "California", "country": "United States", "producer": "Knee Deep Brewing Company", "ba_score": "87", "alcohol": " 8.00%\n\t\t"}
{"website": "brouwerijdemolen.nl", "picture": "https://cdn.beeradvocate.com/im/beers/75365.jpg", "style": "American Amber / Red Ale", "name": "Bed And Breakfast", "ba_ratings": "66", "city": "", "country": "Netherlands", "producer": "Brouwerij De Molen", "ba_score": "79", "alcohol": "\n\t\t"}
{"website": "shortsbrewing.com", "picture": "https://cdn.beeradvocate.com/im/beers/119508.jpg", "style": "American Amber / Red Ale", "name": "Queen Bee", "ba_ratings": "66", "city": "Michigan", "country": "United States", "producer": "Short's Brewing Company", "ba_score": "87", "alcohol": " 8.00%\n\t\t"}
{"website": "bairdbeer.com", "picture": "https://cdn.beeradvocate.com/im/beers/16904.jpg", "style": "American Amber / Red Ale", "name": "Red Rose Amber Ale", "ba_ratings": "86", "city": "", "country": "Japan", "producer": "Baird Brewing Company / Fishmarket Taproom", "ba_score": "85", "alcohol": "\n\t\t"}
{"website": "wineryexchange.com", "picture": "https://cdn.beeradvocate.com/im/beers/31672.jpg", "style": "American Amber / Red Ale", "name": "R.J. King Wingwalker Amber Ale", "ba_ratings": "66", "city": "California", "country": "United States", "producer": "World Brews", "ba_score": "73", "alcohol": " 4.50%\n\t\t"}
{"website": "centralcitybrewing.com", "picture": "https://cdn.beeradvocate.com/im/beers/125139.jpg", "style": "American Amber / Red Ale", "name": "Red Racer Copper Ale", "ba_ratings": "67", "city": "British Columbia", "country": "Canada", "producer": "Central City Brewers + Distillers", "ba_score": "81", "alcohol": " 5.00%\n\t\t"}
{"website": "arborbrewing.com", "picture": "https://cdn.beeradvocate.com/im/beers/5132.jpg", "style": "American Amber / Red Ale", "name": "Arbor Brewing Red Snapper Special Bitter", "ba_ratings": "66", "city": "Michigan", "country": "United States", "producer": "Arbor Brewing Company", "ba_score": "81", "alcohol": " 4.90%\n\t\t"}
{"website": "moosehead.ca", "picture": "https://cdn.beeradvocate.com/im/beers/103343.jpg", "style": "American Amber / Red Ale", "name": "Moosehead Boundary Ale", "ba_ratings": "67", "city": "New Brunswick", "country": "Canada", "producer": "Moosehead Breweries Ltd.", "ba_score": "79", "alcohol": " 5.30%\n\t\t"}
{"website": "crickethillbrewery.com", "picture": "https://cdn.beeradvocate.com/im/beers/45807.jpg", "style": "American Amber / Red Ale", "name": "Fall Festivus", "ba_ratings": "67", "city": "New Jersey", "country": "United States", "producer": "Cricket Hill Brewing Co.", "ba_score": "80", "alcohol": " 4.80%\n\t\t"}
{"website": "dockstreetbeer.com", "picture": "https://cdn.beeradvocate.com/im/beers/4600.jpg", "style": "American Amber / Red Ale", "name": "Dock Street Philadelphia Amber", "ba_ratings": "67", "city": "Pennsylvania", "country": "United States", "producer": "Dock Street Brewery & Restaurant", "ba_score": "82", "alcohol": " 6.00%\n\t\t"}
{"website": "jekyllbrewing.com", "picture": "https://cdn.beeradvocate.com/im/beers/99913.jpg", "style": "American Amber / Red Ale", "name": "'Merican Amber", "ba_ratings": "67", "city": "Georgia", "country": "United States", "producer": "Jekyll Brewing", "ba_score": "83", "alcohol": " 5.80%\n\t\t"}
{"website": "blueandgraybrewingco.com", "picture": "https://cdn.beeradvocate.com/im/beers/9464.jpg", "style": "American Amber / Red Ale", "name": "Fred Red Ale", "ba_ratings": "67", "city": "Virginia", "country": "United States", "producer": "Blue & Gray Brewing Co.", "ba_score": "81", "alcohol": " 6.80%\n\t\t"}
{"website": "jailhousebrewing.com", "picture": "https://cdn.beeradvocate.com/im/beers/78435.jpg", "style": "American Amber / Red Ale", "name": "Misdemeanor", "ba_ratings": "67", "city": "Georgia", "country": "United States", "producer": "Jailhouse Brewing Company", "ba_score": "84", "alcohol": " 5.50%\n\t\t"}
{"website": "603brewery.com", "picture": "https://cdn.beeradvocate.com/im/placeholder-beer.jpg", "style": "American Amber / Red Ale", "name": "Winni Ale", "ba_ratings": "68", "city": "New Hampshire", "country": "United States", "producer": "603 Brewery", "ba_score": "83", "alcohol": " 6.60%\n\t\t"}
{"website": "flyingmonkeybeer.com", "picture": "https://cdn.beeradvocate.com/im/beers/17134.jpg", "style": "American Amber / Red Ale", "name": "Flying Monkey Amber Ale", "ba_ratings": "68", "city": "Kansas", "country": "United States", "producer": "Flying Monkey Brewing Company", "ba_score": "78", "alcohol": " 4.60%\n\t\t"}
{"website": "charlevillevineyard.com", "picture": "https://cdn.beeradvocate.com/im/beers/40711.jpg", "style": "American Amber / Red Ale", "name": "Tornado Alley Amber Ale", "ba_ratings": "68", "city": "Missouri", "country": "United States", "producer": "Charleville Vineyard Microbrewery", "ba_score": "81", "alcohol": " 5.60%\n\t\t"}
{"website": "freetailbrewing.com", "picture": "https://cdn.beeradvocate.com/im/beers/48579.jpg", "style": "American Amber / Red Ale", "name": "Freetail Ale", "ba_ratings": "67", "city": "Texas", "country": "United States", "producer": "Freetail Brewing Company", "ba_score": "85", "alcohol": " 6.00%\n\t\t"}
{"website": "liquidhero.com", "picture": "https://cdn.beeradvocate.com/im/beers/76389.jpg", "style": "American Amber / Red Ale", "name": "American Hero", "ba_ratings": "68", "city": "Pennsylvania", "country": "United States", "producer": "Liquid Hero Brewery", "ba_score": "81", "alcohol": " 5.60%\n\t\t"}
{"website": "firestonewalker.com", "picture": "https://cdn.beeradvocate.com/im/placeholder-beer.jpg", "style": "American Amber / Red Ale", "name": "Rufus", "ba_ratings": "53", "city": "California", "country": "United States", "producer": "Firestone Walker Brewing Co.", "ba_score": "83", "alcohol": " 12.00%\n\t\t"}
{"website": "garrisonbrewing.com", "picture": "https://cdn.beeradvocate.com/im/beers/19759.jpg", "style": "American Amber / Red Ale", "name": "Tall Ship Amber Ale", "ba_ratings": "68", "city": "Nova Scotia", "country": "Canada", "producer": "Garrison Brewing Company", "ba_score": "77", "alcohol": " 4.60%\n\t\t"}
{"website": "coneyislandbeer.com", "picture": "https://cdn.beeradvocate.com/im/beers/160473.jpg", "style": "American Amber / Red Ale", "name": "1609 Amber Ale", "ba_ratings": "54", "city": "New York", "country": "United States", "producer": "Coney Island Brewing Company", "ba_score": "83", "alcohol": " 4.80%\n\t\t"}
{"website": "thirdstreetaleworks.com", "picture": "https://cdn.beeradvocate.com/im/beers/50048.jpg", "style": "American Amber / Red Ale", "name": "Bombay Rouge", "ba_ratings": "67", "city": "California", "country": "United States", "producer": "Third Street Aleworks", "ba_score": "87", "alcohol": " 7.60%\n\t\t"}
{"website": "eelriverbrewing.com", "picture": "https://cdn.beeradvocate.com/im/beers/46056.jpg", "style": "American Amber / Red Ale", "name": "Climax Noel - Imperial Red Ale", "ba_ratings": "54", "city": "California", "country": "United States", "producer": "Eel River Brewing Co.", "ba_score": "83", "alcohol": " 9.20%\n\t\t"}
{"website": "brasseursrj.com", "picture": "https://cdn.beeradvocate.com/im/beers/8034.jpg", "style": "American Amber / Red Ale", "name": "Belle Gueule Rousse", "ba_ratings": "54", "city": "Quebec", "country": "Canada", "producer": "Brasseurs R.J.", "ba_score": "81", "alcohol": " 5.20%\n\t\t"}
{"website": "bluepantsbrew.com", "picture": "https://cdn.beeradvocate.com/im/placeholder-beer.jpg", "style": "American Amber / Red Ale", "name": "Knickerbocker Red", "ba_ratings": "54", "city": "Alabama", "country": "United States", "producer": "Blue Pants Brewery", "ba_score": "82", "alcohol": " 7.00%\n\t\t"}
{"website": "hawaiinuibrewing.com", "picture": "https://cdn.beeradvocate.com/im/beers/8430.jpg", "style": "American Amber / Red Ale", "name": "Mehana Volcano Red Ale", "ba_ratings": "55", "city": "Hawaii", "country": "United States", "producer": "Hawai'i Nui Brewing / Mehana Brewing Company", "ba_score": "78", "alcohol": " 5.20%\n\t\t"}
{"website": "denalibrewingcompany.com", "picture": "https://cdn.beeradvocate.com/im/beers/71744.jpg", "style": "American Amber / Red Ale", "name": "Single Engine Red", "ba_ratings": "54", "city": "Alaska", "country": "United States", "producer": "Denali Brewing Company / Twister Creek Restaurant", "ba_score": "83", "alcohol": " 5.60%\n\t\t"}
{"website": "cigarcitybrewing.com", "picture": "https://cdn.beeradvocate.com/im/placeholder-beer.jpg", "style": "American Amber / Red Ale", "name": "Citrus Wizard", "ba_ratings": "55", "city": "Florida", "country": "United States", "producer": "Cigar City Brewing", "ba_score": "91", "alcohol": " 7.20%\n\t\t"}
{"website": "flat12.me", "picture": "https://cdn.beeradvocate.com/im/placeholder-beer.jpg", "style": "American Amber / Red Ale", "name": "Moustache Ride", "ba_ratings": "55", "city": "Indiana", "country": "United States", "producer": "Flat 12 Bierwerks", "ba_score": "86", "alcohol": " 6.00%\n\t\t"}
{"website": "graybrewing.com", "picture": "https://cdn.beeradvocate.com/im/beers/25145.jpg", "style": "American Amber / Red Ale", "name": "Rathskeller Amber Ale", "ba_ratings": "55", "city": "Wisconsin", "country": "United States", "producer": "Gray's Brewing Company", "ba_score": "78", "alcohol": " 5.50%\n\t\t"}
{"website": "fortcollinsbrewery.com", "picture": "https://cdn.beeradvocate.com/im/beers/52533.jpg", "style": "American Amber / Red Ale", "name": "Common Ground", "ba_ratings": "54", "city": "Colorado", "country": "United States", "producer": "The Fort Collins Brewery", "ba_score": "81", "alcohol": " 5.60%\n\t\t"}
{"website": "minhasbrewery.com", "picture": "https://cdn.beeradvocate.com/im/beers/45972.jpg", "style": "American Amber / Red Ale", "name": "Minhas Swiss Style Amber", "ba_ratings": "55", "city": "Wisconsin", "country": "United States", "producer": "Minhas Craft Brewery", "ba_score": "72", "alcohol": " 5.50%\n\t\t"}
{"website": "ypguides.net", "picture": "https://cdn.beeradvocate.com/im/beers/955.jpg", "style": "American Amber / Red Ale", "name": "Nightwatch Dark Amber Ale", "ba_ratings": "56", "city": "Washington", "country": "United States", "producer": "Maritime Pacific Brewing Company", "ba_score": "82", "alcohol": " 5.50%\n\t\t"}
{"website": "tritonbrewing.com", "picture": "https://cdn.beeradvocate.com/im/beers/75656.jpg", "style": "American Amber / Red Ale", "name": "Magnificent Amber", "ba_ratings": "56", "city": "Indiana", "country": "United States", "producer": "Triton Brewing Company", "ba_score": "83", "alcohol": " 5.30%\n\t\t"}
{"website": "backcountrybrewery.com", "picture": "https://cdn.beeradvocate.com/im/placeholder-beer.jpg", "style": "American Amber / Red Ale", "name": "Backcountry Amber", "ba_ratings": "57", "city": "Colorado", "country": "United States", "producer": "Backcountry Brewery", "ba_score": "82", "alcohol": " 5.38%\n\t\t"}
{"website": "barrierbrewing.com", "picture": "https://cdn.beeradvocate.com/im/placeholder-beer.jpg", "style": "American Amber / Red Ale", "name": "Bulkhead Red", "ba_ratings": "57", "city": "New York", "country": "United States", "producer": "Barrier Brewing Company", "ba_score": "87", "alcohol": " 6.50%\n\t\t"}
{"website": "hoppy.com", "picture": "https://cdn.beeradvocate.com/im/beers/9269.jpg", "style": "American Amber / Red Ale", "name": "Stony Face Red Ale", "ba_ratings": "57", "city": "California", "country": "United States", "producer": "Hoppy Brewing Co.", "ba_score": "81", "alcohol": " 5.60%\n\t\t"}
{"website": "destihlbrewery.com", "picture": "https://cdn.beeradvocate.com/im/beers/55983.jpg", "style": "American Amber / Red Ale", "name": "DeadHead Double Red Ale", "ba_ratings": "58", "city": "Illinois", "country": "United States", "producer": "DESTIHL Brewery", "ba_score": "86", "alcohol": " 9.10%\n\t\t"}
{"website": "radiantpigbeer.com", "picture": "https://cdn.beeradvocate.com/im/placeholder-beer.jpg", "style": "American Amber / Red Ale", "name": "Gangster Duck", "ba_ratings": "48", "city": "New York", "country": "United States", "producer": "Radiant Pig Craft Beers", "ba_score": "85", "alcohol": " 6.20%\n\t\t"}
{"website": "gooseisland.com", "picture": "https://cdn.beeradvocate.com/im/beers/3478.jpg", "style": "American Amber / Red Ale", "name": "Red Felt Ale", "ba_ratings": "56", "city": "Illinois", "country": "United States", "producer": "Goose Island Beer Co.", "ba_score": "88", "alcohol": " 6.00%\n\t\t"}
{"website": "hennikerbrewing.com", "picture": "https://cdn.beeradvocate.com/im/beers/89398.jpg", "style": "American Amber / Red Ale", "name": "Amber Apparition", "ba_ratings": "56", "city": "New Hampshire", "country": "United States", "producer": "Henniker Brewing Co.", "ba_score": "82", "alcohol": " 5.20%\n\t\t"}
{"website": "ubuale.com", "picture": "https://cdn.beeradvocate.com/im/beers/11279.jpg", "style": "American Amber / Red Ale", "name": "Barkeater Amber Ale", "ba_ratings": "57", "city": "New York", "country": "United States", "producer": "Lake Placid Craft Brewing Company", "ba_score": "81", "alcohol": " 5.00%\n\t\t"}
{"website": "mountaintownbrew.com", "picture": "https://cdn.beeradvocate.com/im/beers/40929.jpg", "style": "American Amber / Red Ale", "name": "Cow Catcher Red Ale", "ba_ratings": "57", "city": "Michigan", "country": "United States", "producer": "Mountain Town Brewing Co.", "ba_score": "81", "alcohol": " 5.80%\n\t\t"}
{"website": "drinkrangercreek.com", "picture": "https://cdn.beeradvocate.com/im/beers/101707.jpg", "style": "American Amber / Red Ale", "name": "Red Headed Stranger", "ba_ratings": "48", "city": "Texas", "country": "United States", "producer": "Ranger Creek Brewing & Distilling", "ba_score": "84", "alcohol": " 6.30%\n\t\t"}
{"website": "newalbanian.com", "picture": "https://cdn.beeradvocate.com/im/beers/35631.jpg", "style": "American Amber / Red Ale", "name": "Hoosier Daddy", "ba_ratings": "45", "city": "Indiana", "country": "United States", "producer": "New Albanian Brewing Company - Pizzeria and Public House", "ba_score": "83", "alcohol": " 7.00%\n\t\t"}
{"website": "oldcreditbrewing.com", "picture": "https://cdn.beeradvocate.com/im/beers/8694.jpg", "style": "American Amber / Red Ale", "name": "Old Credit Amber Ale", "ba_ratings": "46", "city": "Ontario", "country": "Canada", "producer": "Old Credit Brewing Co.", "ba_score": "78", "alcohol": " 5.00%\n\t\t"}
{"website": "riverhorse.com", "picture": "https://cdn.beeradvocate.com/im/beers/43769.jpg", "style": "American Amber / Red Ale", "name": "Imperial Cherry Amber Ale", "ba_ratings": "46", "city": "New Jersey", "country": "United States", "producer": "River Horse Brewing Co.", "ba_score": "80", "alcohol": " 7.50%\n\t\t"}
{"website": "yourbrewery.com", "picture": "https://cdn.beeradvocate.com/im/placeholder-beer.jpg", "style": "American Amber / Red Ale", "name": "Enchanted Rock Red Ale", "ba_ratings": "46", "city": "Texas", "country": "United States", "producer": "Fredericksburg Brewing Company, Inc.", "ba_score": "79", "alcohol": " 5.30%\n\t\t"}
{"website": "berghoffbeer.com", "picture": "https://cdn.beeradvocate.com/im/beers/96988.jpg", "style": "American Amber / Red Ale", "name": "Reppin' Red Ale", "ba_ratings": "46", "city": "Illinois", "country": "United States", "producer": "Berghoff Brewery", "ba_score": "78", "alcohol": " 6.20%\n\t\t"}
{"website": "deschutesbrewery.com", "picture": "https://cdn.beeradvocate.com/im/beers/243763.jpg", "style": "American Amber / Red Ale", "name": "Swivelhead Red India Style Red Ale", "ba_ratings": "46", "city": "Oregon", "country": "United States", "producer": "Deschutes Brewery", "ba_score": "84", "alcohol": " 6.50%\n\t\t"}
{"website": "nolabrewing.com", "picture": "https://cdn.beeradvocate.com/im/beers/65374.jpg", "style": "American Amber / Red Ale", "name": "Flambeau Red", "ba_ratings": "46", "city": "Louisiana", "country": "United States", "producer": "New Orleans Lager & Ale Brewing Company (NOLA)", "ba_score": "88", "alcohol": " 5.70%\n\t\t"}
{"website": "steamworksbrewing.com", "picture": "https://cdn.beeradvocate.com/im/beers/10728.jpg", "style": "American Amber / Red Ale", "name": "Lizard Head Red", "ba_ratings": "47", "city": "Colorado", "country": "United States", "producer": "Steamworks Brewing Co.", "ba_score": "81", "alcohol": " 5.50%\n\t\t"}
{"website": "prescottbrewingcompany.com", "picture": "https://cdn.beeradvocate.com/im/beers/4423.jpg", "style": "American Amber / Red Ale", "name": "Liquid Amber", "ba_ratings": "47", "city": "Arizona", "country": "United States", "producer": "Prescott Brewing Company", "ba_score": "82", "alcohol": " not listed\n\t\t"}
{"website": "orlandobrewing.com", "picture": "https://cdn.beeradvocate.com/im/beers/40410.jpg", "style": "American Amber / Red Ale", "name": "Red Ale", "ba_ratings": "48", "city": "Florida", "country": "United States", "producer": "Orlando Brewing Partners", "ba_score": "79", "alcohol": " 5.80%\n\t\t"}
{"website": "fishbrewing.com", "picture": "https://cdn.beeradvocate.com/im/beers/70845.jpg", "style": "American Amber / Red Ale", "name": "Starfish Imperial Red Ale", "ba_ratings": "48", "city": "Washington", "country": "United States", "producer": "Fish Brewing Company / Fishbowl Brewpub", "ba_score": "82", "alcohol": " 7.50%\n\t\t"}
{"website": "myrivertowne.com", "picture": "https://cdn.beeradvocate.com/im/beers/117311.jpg", "style": "American Amber / Red Ale", "name": "Patrick's Poison", "ba_ratings": "47", "city": "Pennsylvania", "country": "United States", "producer": "Rivertowne Brewing", "ba_score": "85", "alcohol": " 8.00%\n\t\t"}
{"website": "3dbrewing.com", "picture": "https://cdn.beeradvocate.com/im/beers/179823.jpg", "style": "American Amber / Red Ale", "name": "Rod Bender", "ba_ratings": "48", "city": "Florida", "country": "United States", "producer": "3 Daughters Brewing", "ba_score": "81", "alcohol": " 5.90%\n\t\t"}
{"website": "fishbrewing.com", "picture": "https://cdn.beeradvocate.com/im/beers/26207.jpg", "style": "American Amber / Red Ale", "name": "Leavenworth Oktoberfest Celebration Ale", "ba_ratings": "47", "city": "Washington", "country": "United States", "producer": "Fish Brewing Company / Fishbowl Brewpub", "ba_score": "83", "alcohol": " 5.50%\n\t\t"}
{"website": "berghoffbeer.com", "picture": "https://cdn.beeradvocate.com/im/beers/45439.jpg", "style": "American Amber / Red Ale", "name": "Rock River Red Ale", "ba_ratings": "47", "city": "Illinois", "country": "United States", "producer": "Berghoff Brewery", "ba_score": "74", "alcohol": " not listed\n\t\t"}
{"website": "fcbrewing.com", "picture": "https://cdn.beeradvocate.com/im/beers/167084.jpg", "style": "American Amber / Red Ale", "name": "Heart O' Texas", "ba_ratings": "48", "city": "Texas", "country": "United States", "producer": "Four Corners Brewing Company", "ba_score": "82", "alcohol": " 6.20%\n\t\t"}
{"website": "branchlinebrewing.com", "picture": "https://cdn.beeradvocate.com/im/placeholder-beer.jpg", "style": "American Amber / Red Ale", "name": "Evil Owl Amber", "ba_ratings": "49", "city": "Texas", "country": "United States", "producer": "Branchline Brewing Co.", "ba_score": "83", "alcohol": " 5.20%\n\t\t"}
{"website": "greenmanbrewery.com", "picture": "https://cdn.beeradvocate.com/im/placeholder-beer.jpg", "style": "American Amber / Red Ale", "name": "Green Man Leaf Blower Whole Leaf Amber", "ba_ratings": "48", "city": "North Carolina", "country": "United States", "producer": "Green Man Brewery", "ba_score": "82", "alcohol": " 6.20%\n\t\t"}
{"website": "newrepublicbrewing.com", "picture": "https://cdn.beeradvocate.com/im/beers/100417.jpg", "style": "American Amber / Red Ale", "name": "Dammit Jim!", "ba_ratings": "40", "city": "Texas", "country": "United States", "producer": "New Republic Brewing Company", "ba_score": "84", "alcohol": " 5.60%\n\t\t"}
{"website": "kodawari.cc", "picture": "https://cdn.beeradvocate.com/im/beers/7729.jpg", "style": "American Amber / Red Ale", "name": "Hitachino Nest Amber Ale", "ba_ratings": "41", "city": "", "country": "Japan", "producer": "Kiuchi Brewery", "ba_score": "85", "alcohol": "\n\t\t"}
{"website": "doubletakebrewing.com", "picture": "https://cdn.beeradvocate.com/im/beers/70552.jpg", "style": "American Amber / Red Ale", "name": "Amber Ale", "ba_ratings": "41", "city": "New York", "country": "United States", "producer": "Double Take Brewing Company", "ba_score": "75", "alcohol": " 5.10%\n\t\t"}
{"website": "portsmouthbrewery.com", "picture": "https://cdn.beeradvocate.com/im/beers/20146.jpg", "style": "American Amber / Red Ale", "name": "Portsmouth Hop Harvest #1", "ba_ratings": "41", "city": "New Hampshire", "country": "United States", "producer": "Portsmouth Brewery", "ba_score": "87", "alcohol": " 6.50%\n\t\t"}
{"website": "lighthousebrewing.com", "picture": "https://cdn.beeradvocate.com/im/beers/87871.jpg", "style": "American Amber / Red Ale", "name": "Siren Red Ale", "ba_ratings": "41", "city": "British Columbia", "country": "Canada", "producer": "Lighthouse Brewing Company", "ba_score": "88", "alcohol": " 8.00%\n\t\t"}
{"website": "fishbrewing.com", "picture": "https://cdn.beeradvocate.com/im/beers/104395.jpg", "style": "American Amber / Red Ale", "name": "Vicious Circle Amber Ale", "ba_ratings": "49", "city": "Washington", "country": "United States", "producer": "Fish Brewing Company / Fishbowl Brewpub", "ba_score": "83", "alcohol": " 5.00%\n\t\t"}
{"website": "tapitbrewing.com", "picture": "https://cdn.beeradvocate.com/im/beers/92144.jpg", "style": "American Amber / Red Ale", "name": "Ale Camino", "ba_ratings": "42", "city": "California", "country": "United States", "producer": "Tap It Brewing Co.", "ba_score": "82", "alcohol": " 5.50%\n\t\t"}
{"website": "funkybuddhabrewery.com", "picture": "https://cdn.beeradvocate.com/im/placeholder-beer.jpg", "style": "American Amber / Red Ale", "name": "Fuhgeddaboudit", "ba_ratings": "42", "city": "Florida", "country": "United States", "producer": "Funky Buddha Brewery", "ba_score": "84", "alcohol": " 5.40%\n\t\t"}
{"website": "elevationbeerco.com", "picture": "https://cdn.beeradvocate.com/im/beers/88331.jpg", "style": "American Amber / Red Ale", "name": "Downpour", "ba_ratings": "41", "city": "Colorado", "country": "United States", "producer": "Elevation Beer Co.", "ba_score": "86", "alcohol": " 8.30%\n\t\t"}
{"website": "boneyardbeer.com", "picture": "https://cdn.beeradvocate.com/im/beers/75832.jpg", "style": "American Amber / Red Ale", "name": "Skunk Ape", "ba_ratings": "41", "city": "Oregon", "country": "United States", "producer": "Boneyard Beer Company", "ba_score": "86", "alcohol": " 6.00%\n\t\t"}
{"website": "breweryterrafirma.com", "picture": "https://cdn.beeradvocate.com/im/beers/102959.jpg", "style": "American Amber / Red Ale", "name": "Manitou Amber Ale", "ba_ratings": "41", "city": "Michigan", "country": "United States", "producer": "Brewery Terra Firma", "ba_score": "84", "alcohol": " 5.30%\n\t\t"}
{"website": "boulderbeer.com", "picture": "https://cdn.beeradvocate.com/im/placeholder-beer.jpg", "style": "American Amber / Red Ale", "name": "Freshtracks Wet Hopped Ale", "ba_ratings": "42", "city": "Colorado", "country": "United States", "producer": "Boulder Beer / Wilderness Pub", "ba_score": "83", "alcohol": " 4.90%\n\t\t"}
{"website": null, "picture": "https://cdn.beeradvocate.com/im/placeholder-beer.jpg", "style": "American Amber / Red Ale", "name": "Copperhead Amber Ale", "ba_ratings": "42", "city": "Mississippi", "country": "United States", "producer": "Yalobusha Brewing Company", "ba_score": "84", "alcohol": " 5.65%\n\t\t"}
{"website": "theblackhorsepub.net", "picture": "https://cdn.beeradvocate.com/im/placeholder-beer.jpg", "style": "American Amber / Red Ale", "name": "Barnstormer Red", "ba_ratings": "42", "city": "Tennessee", "country": "United States", "producer": "Blackhorse Pub & Brewery", "ba_score": "78", "alcohol": " not listed\n\t\t"}
{"website": "greatnorthernbrewing.com", "picture": "https://cdn.beeradvocate.com/im/beers/84895.jpg", "style": "American Amber / Red Ale", "name": "Good Medicine Strong Red Ale", "ba_ratings": "42", "city": "Montana", "country": "United States", "producer": "Great Northern Brewing Co. / Black Star Draught House", "ba_score": "86", "alcohol": " 7.50%\n\t\t"}
{"website": "trailheadbrewing.com", "picture": "https://cdn.beeradvocate.com/im/beers/6729.jpg", "style": "American Amber / Red Ale", "name": "Trailhead Red", "ba_ratings": "42", "city": "Missouri", "country": "United States", "producer": "Trailhead Brewing Co", "ba_score": "78", "alcohol": " not listed\n\t\t"}
{"website": "epicbrewing.com", "picture": "https://cdn.beeradvocate.com/im/beers/58952.jpg", "style": "American Amber / Red Ale", "name": "Cross Fever", "ba_ratings": "42", "city": "Utah", "country": "United States", "producer": "Epic Brewing Company", "ba_score": "80", "alcohol": " 4.80%\n\t\t"}
{"website": "thebrewkettle.com", "picture": "https://cdn.beeradvocate.com/im/beers/18923.jpg", "style": "American Amber / Red Ale", "name": "Copperhead Red", "ba_ratings": "42", "city": "Ohio", "country": "United States", "producer": "The Brew Kettle Taproom & Smokehouse / Production Works", "ba_score": "81", "alcohol": " 5.00%\n\t\t"}
{"website": "coldspringbrewery.com", "picture": "https://cdn.beeradvocate.com/im/beers/37996.jpg", "style": "American Amber / Red Ale", "name": "Olde Johnnie Ale", "ba_ratings": "42", "city": "Minnesota", "country": "United States", "producer": "Cold Spring Brewing Co.", "ba_score": "79", "alcohol": " 4.70%\n\t\t"}
{"website": "stillmankbrewing.com", "picture": "https://cdn.beeradvocate.com/im/beers/97317.jpg", "style": "American Amber / Red Ale", "name": "Wisco Disco", "ba_ratings": "42", "city": "Wisconsin", "country": "United States", "producer": "Stillmank Beer Company", "ba_score": "82", "alcohol": " 5.10%\n\t\t"}
{"website": "blackshirtbrewingco.com", "picture": "https://cdn.beeradvocate.com/im/beers/117766.jpg", "style": "American Amber / Red Ale", "name": "American India Red Ale", "ba_ratings": "35", "city": "Colorado", "country": "United States", "producer": "Black Shirt Brewing Co.", "ba_score": "75", "alcohol": " 7.18%\n\t\t"}
