{"website": "newbelgium.com", "picture": "https://cdn.beeradvocate.com/im/beers/607.jpg", "style": "American Amber / Red Ale", "name": "Fat Tire Amber Ale", "ba_ratings": "8,608", "city": "Colorado", "country": "United States", "producer": "New Belgium Brewing", "ba_score": "82", "alcohol": " 5.20%\n\t\t"}
{"website": "avbc.com", "picture": "https://cdn.beeradvocate.com/im/beers/623.jpg", "style": "American Amber / Red Ale", "name": "Boont Amber Ale", "ba_ratings": "1,564", "city": "California", "country": "United States", "producer": "Anderson Valley Brewing Company", "ba_score": "86", "alcohol": " 5.80%\n\t\t"}
{"website": "highlandbrewing.com", "picture": "https://cdn.beeradvocate.com/im/beers/2526.jpg", "style": "American Amber / Red Ale", "name": "Highland Gaelic Ale", "ba_ratings": "1,467", "city": "North Carolina", "country": "United States", "producer": "Highland Brewing", "ba_score": "86", "alcohol": " 5.80%\n\t\t"}
{"website": "bearrepublic.com", "picture": "https://cdn.beeradvocate.com/im/beers/1655.jpg", "style": "American Amber / Red Ale", "name": "Red Rocket Ale", "ba_ratings": "2,602", "city": "California", "country": "United States", "producer": "Bear Republic Brewing Co.", "ba_score": "91", "alcohol": " 6.80%\n\t\t"}
{"website": "mainebeercompany.com", "picture": "https://cdn.beeradvocate.com/im/beers/54522.jpg", "style": "American Amber / Red Ale", "name": "Zoe", "ba_ratings": "2,465", "city": "Maine", "country": "United States", "producer": "Maine Beer Company", "ba_score": "93", "alcohol": " 7.20%\n\t\t"}
{"website": "averybrewing.com", "picture": "https://cdn.beeradvocate.com/im/beers/1490.jpg", "style": "American Amber / Red Ale", "name": "Hog Heaven: Imperial Red IPA", "ba_ratings": "2,069", "city": "Colorado", "country": "United States", "producer": "Avery Brewing Company", "ba_score": "89", "alcohol": " 9.20%\n\t\t"}
{"website": "greatlakesbrewing.com", "picture": "https://cdn.beeradvocate.com/im/beers/1792.jpg", "style": "American Amber / Red Ale", "name": "Great Lakes Nosferatu", "ba_ratings": "2,606", "city": "Ohio", "country": "United States", "producer": "Great Lakes Brewing Co.", "ba_score": "91", "alcohol": " 8.00%\n\t\t"}
{"website": "northcoastbrewing.com", "picture": "https://cdn.beeradvocate.com/im/beers/410.jpg", "style": "American Amber / Red Ale", "name": "Ruedrich's Red Seal Ale", "ba_ratings": "2,069", "city": "California", "country": "United States", "producer": "North Coast Brewing Co.", "ba_score": "88", "alcohol": " 5.40%\n\t\t"}
{"website": "rogue.com", "picture": "https://cdn.beeradvocate.com/im/beers/1173.jpg", "style": "American Amber / Red Ale", "name": "Santa's Private Reserve Ale", "ba_ratings": "2,338", "city": "Oregon", "country": "United States", "producer": "Rogue Ales", "ba_score": "85", "alcohol": " 5.30%\n\t\t"}
{"website": "lagunitas.com", "picture": "https://cdn.beeradvocate.com/im/beers/35397.jpg", "style": "American Amber / Red Ale", "name": "Lagunitas Lucky 13 Mondo Large Red Ale", "ba_ratings": "2,650", "city": "California", "country": "United States", "producer": "Lagunitas Brewing Company", "ba_score": "91", "alcohol": " 8.80%\n\t\t"}
{"website": "lagunitas.com", "picture": "https://cdn.beeradvocate.com/im/beers/3711.jpg", "style": "American Amber / Red Ale", "name": "Censored", "ba_ratings": "2,721", "city": "California", "country": "United States", "producer": "Lagunitas Brewing Company", "ba_score": "85", "alcohol": " 6.75%\n\t\t"}
{"website": "sierranevada.com", "picture": "https://cdn.beeradvocate.com/im/beers/98495.jpg", "style": "American Amber / Red Ale", "name": "Flipside Red IPA", "ba_ratings": "2,858", "city": "California", "country": "United States", "producer": "Sierra Nevada Brewing Co.", "ba_score": "86", "alcohol": " 6.20%\n\t\t"}
{"website": "greenflashbrew.com", "picture": "https://cdn.beeradvocate.com/im/beers/35732.jpg", "style": "American Amber / Red Ale", "name": "Green Flash Hop Head Red Ale", "ba_ratings": "3,402", "city": "California", "country": "United States", "producer": "Green Flash Brewing Co.", "ba_score": "90", "alcohol": " 8.10%\n\t\t"}
{"website": "troegs.com", "picture": "https://cdn.beeradvocate.com/im/beers/15881.jpg", "style": "American Amber / Red Ale", "name": "Tr\u00f6egs Nugget Nectar", "ba_ratings": "8,551", "city": "Pennsylvania", "country": "United States", "producer": "Tr\u00f6egs Brewing Company", "ba_score": "96", "alcohol": " 7.50%\n\t\t"}
{"website": "troegs.com", "picture": "https://cdn.beeradvocate.com/im/beers/6322.jpg", "style": "American Amber / Red Ale", "name": "Tr\u00f6egs Hopback Amber Ale", "ba_ratings": "3,079", "city": "Pennsylvania", "country": "United States", "producer": "Tr\u00f6egs Brewing Company", "ba_score": "90", "alcohol": " 6.00%\n\t\t"}
{"website": "bellsbeer.com", "picture": "https://cdn.beeradvocate.com/im/beers/794.jpg", "style": "American Amber / Red Ale", "name": "Bell's Amber Ale", "ba_ratings": "3,101", "city": "Michigan", "country": "United States", "producer": "Bell's Brewery, Inc.", "ba_score": "87", "alcohol": " 5.80%\n\t\t"}
{"website": "coronadobrewing.com", "picture": "https://cdn.beeradvocate.com/im/beers/14236.jpg", "style": "American Amber / Red Ale", "name": "Mermaid's Red Ale", "ba_ratings": "550", "city": "California", "country": "United States", "producer": "Coronado Brewing Company", "ba_score": "82", "alcohol": " 5.70%\n\t\t"}
{"website": "alesmith.com", "picture": "https://cdn.beeradvocate.com/im/beers/10387.jpg", "style": "American Amber / Red Ale", "name": "AleSmith Evil Dead Red", "ba_ratings": "547", "city": "California", "country": "United States", "producer": "AleSmith Brewing Company", "ba_score": "91", "alcohol": " 6.66%\n\t\t"}
{"website": "weyerbacher.com", "picture": "https://cdn.beeradvocate.com/im/placeholder-beer.jpg", "style": "American Amber / Red Ale", "name": "AutumnFest", "ba_ratings": "561", "city": "Pennsylvania", "country": "United States", "producer": "Weyerbacher Brewing Co.", "ba_score": "81", "alcohol": " 5.40%\n\t\t"}
{"website": "bridgeportbrew.com", "picture": "https://cdn.beeradvocate.com/im/beers/64798.jpg", "style": "American Amber / Red Ale", "name": "Kingpin Double Red Ale", "ba_ratings": "558", "city": "Oregon", "country": "United States", "producer": "BridgePort Brewing Co. / Brewpub", "ba_score": "80", "alcohol": " 7.50%\n\t\t"}
{"website": "pdubs.net", "picture": "https://cdn.beeradvocate.com/im/beers/81742.jpg", "style": "American Amber / Red Ale", "name": "Blood Of The Unicorn", "ba_ratings": "649", "city": "Illinois", "country": "United States", "producer": "Pipeworks Brewing Company", "ba_score": "89", "alcohol": " 6.50%\n\t\t"}
{"website": "portbrewing.com", "picture": "https://cdn.beeradvocate.com/im/beers/41421.jpg", "style": "American Amber / Red Ale", "name": "Shark Attack Double Red Ale", "ba_ratings": "774", "city": "California", "country": "United States", "producer": "Port Brewing", "ba_score": "87", "alcohol": " 9.00%\n\t\t"}
{"website": "alesmith.com", "picture": "https://cdn.beeradvocate.com/im/beers/28312.jpg", "style": "American Amber / Red Ale", "name": "AleSmith My Bloody Valentine", "ba_ratings": "672", "city": "California", "country": "United States", "producer": "AleSmith Brewing Company", "ba_score": "89", "alcohol": " 6.66%\n\t\t"}
{"website": "revbrew.com", "picture": "https://cdn.beeradvocate.com/im/beers/64036.jpg", "style": "American Amber / Red Ale", "name": "Fistmas", "ba_ratings": "621", "city": "Illinois", "country": "United States", "producer": "Revolution Brewing", "ba_score": "86", "alcohol": " 6.10%\n\t\t"}
{"website": "odells.com", "picture": "https://cdn.beeradvocate.com/im/beers/47589.jpg", "style": "American Amber / Red Ale", "name": "Runoff Red IPA", "ba_ratings": "791", "city": "Colorado", "country": "United States", "producer": "Odell Brewing Company", "ba_score": "90", "alcohol": " 6.50%\n\t\t"}
{"website": "rogue.com", "picture": "https://cdn.beeradvocate.com/im/beers/51071.jpg", "style": "American Amber / Red Ale", "name": "Captain Sig's Northwestern Ale", "ba_ratings": "804", "city": "Oregon", "country": "United States", "producer": "Rogue Ales", "ba_score": "85", "alcohol": " 6.20%\n\t\t"}
{"website": "newbelgium.com", "picture": "https://cdn.beeradvocate.com/im/beers/83434.jpg", "style": "American Amber / Red Ale", "name": "Red Hoptober", "ba_ratings": "810", "city": "Colorado", "country": "United States", "producer": "New Belgium Brewing", "ba_score": "86", "alcohol": " 6.00%\n\t\t"}
{"website": "switchbackvt.com", "picture": "https://cdn.beeradvocate.com/im/beers/11960.jpg", "style": "American Amber / Red Ale", "name": "Switchback Ale", "ba_ratings": "834", "city": "Vermont", "country": "United States", "producer": "Switchback Brewing Company", "ba_score": "81", "alcohol": " 5.00%\n\t\t"}
{"website": "calderabrewing.com", "picture": "https://cdn.beeradvocate.com/im/beers/10785.jpg", "style": "American Amber / Red Ale", "name": "Ashland Amber", "ba_ratings": "276", "city": "Oregon", "country": "United States", "producer": "Caldera Brewing Company", "ba_score": "84", "alcohol": " 5.40%\n\t\t"}
{"website": "centralwaters.com", "picture": "https://cdn.beeradvocate.com/im/beers/3997.jpg", "style": "American Amber / Red Ale", "name": "Ouisconsing Red Ale", "ba_ratings": "277", "city": "Wisconsin", "country": "United States", "producer": "Central Waters Brewing Co.", "ba_score": "81", "alcohol": " 4.80%\n\t\t"}
{"website": "mayflowerbrewing.com", "picture": "https://cdn.beeradvocate.com/im/beers/67109.jpg", "style": "American Amber / Red Ale", "name": "Mayflower Spring Hop", "ba_ratings": "278", "city": "Massachusetts", "country": "United States", "producer": "Mayflower Brewing Company", "ba_score": "90", "alcohol": " 5.30%\n\t\t"}
{"website": "jackieos.com", "picture": "https://cdn.beeradvocate.com/im/beers/58983.jpg", "style": "American Amber / Red Ale", "name": "Firefly Amber Ale", "ba_ratings": "284", "city": "Ohio", "country": "United States", "producer": "Jackie O's Pub & Brewery", "ba_score": "80", "alcohol": " 4.50%\n\t\t"}
{"website": "gooseisland.com", "picture": "https://cdn.beeradvocate.com/im/beers/21024.jpg", "style": "American Amber / Red Ale", "name": "Goose Autumn Ale", "ba_ratings": "279", "city": "Illinois", "country": "United States", "producer": "Goose Island Beer Co.", "ba_score": "84", "alcohol": " 6.70%\n\t\t"}
{"website": "21st-amendment.com", "picture": "https://cdn.beeradvocate.com/im/beers/185213.jpg", "style": "American Amber / Red Ale", "name": "Toaster Pastry", "ba_ratings": "614", "city": "California", "country": "United States", "producer": "21st Amendment Brewery", "ba_score": "89", "alcohol": " 7.60%\n\t\t"}
{"website": "rogue.com", "picture": "https://cdn.beeradvocate.com/im/beers/40187.jpg", "style": "American Amber / Red Ale", "name": "XS Imperial Red", "ba_ratings": "291", "city": "Oregon", "country": "United States", "producer": "Rogue Ales", "ba_score": "85", "alcohol": " 9.00%\n\t\t"}
{"website": "humboldtbrewingco.com", "picture": "https://cdn.beeradvocate.com/im/beers/1663.jpg", "style": "American Amber / Red Ale", "name": "Red Nectar", "ba_ratings": "587", "city": "California", "country": "United States", "producer": "Humboldt Brewing Co.", "ba_score": "83", "alcohol": " 5.40%\n\t\t"}
{"website": "redhook.com", "picture": "https://cdn.beeradvocate.com/im/beers/28712.jpg", "style": "American Amber / Red Ale", "name": "Redhook Late Harvest Autumn Ale", "ba_ratings": "294", "city": "New Hampshire", "country": "United States", "producer": "Redhook Ale Brewery", "ba_score": "79", "alcohol": " 5.90%\n\t\t"}
{"website": "aleasylum.com", "picture": "https://cdn.beeradvocate.com/im/beers/31117.jpg", "style": "American Amber / Red Ale", "name": "Ambergeddon", "ba_ratings": "587", "city": "Wisconsin", "country": "United States", "producer": "Ale Asylum", "ba_score": "89", "alcohol": " 6.80%\n\t\t"}
{"website": "elysianbrewing.com", "picture": "https://cdn.beeradvocate.com/im/beers/59248.jpg", "style": "American Amber / Red Ale", "name": "The Men's Room Ale", "ba_ratings": "296", "city": "Washington", "country": "United States", "producer": "Elysian Brewing Company", "ba_score": "82", "alcohol": " 5.60%\n\t\t"}
{"website": "skabrewing.com", "picture": "https://cdn.beeradvocate.com/im/beers/3148.jpg", "style": "American Amber / Red Ale", "name": "Pinstripe Red Ale", "ba_ratings": "332", "city": "Colorado", "country": "United States", "producer": "Ska Brewing Co.", "ba_score": "80", "alcohol": " 5.15%\n\t\t"}
{"website": "ofallonbrewery.com", "picture": "https://cdn.beeradvocate.com/im/beers/56887.jpg", "style": "American Amber / Red Ale", "name": "Hemp Hop Rye", "ba_ratings": "329", "city": "Missouri", "country": "United States", "producer": "O'Fallon Brewery", "ba_score": "81", "alcohol": " 5.50%\n\t\t"}
{"website": "coors.com", "picture": "https://cdn.beeradvocate.com/im/beers/40528.jpg", "style": "American Amber / Red Ale", "name": "Blue Moon Rising Moon Spring Ale", "ba_ratings": "350", "city": "Colorado", "country": "United States", "producer": "Coors Brewing Company", "ba_score": "71", "alcohol": " 5.40%\n\t\t"}
{"website": "newbelgium.com", "picture": "https://cdn.beeradvocate.com/im/beers/217618.jpg", "style": "American Amber / Red Ale", "name": "Fat Tire And Friends Fat Hoppy Ale", "ba_ratings": "360", "city": "Colorado", "country": "United States", "producer": "New Belgium Brewing", "ba_score": "89", "alcohol": " 6.00%\n\t\t"}
{"website": "nattygreenes.com", "picture": "https://cdn.beeradvocate.com/im/beers/19165.jpg", "style": "American Amber / Red Ale", "name": "Buckshot Amber Ale", "ba_ratings": "373", "city": "North Carolina", "country": "United States", "producer": "Natty Greene's Pub & Brewing Co.", "ba_score": "79", "alcohol": " 4.90%\n\t\t"}
{"website": "belfastbaybrewing.com", "picture": "https://cdn.beeradvocate.com/im/beers/2532.jpg", "style": "American Amber / Red Ale", "name": "Lobster Ale", "ba_ratings": "308", "city": "Maine", "country": "United States", "producer": "Belfast Bay Brewing Co.", "ba_score": "80", "alcohol": " 5.00%\n\t\t"}
{"website": "twobrothersbrewing.com", "picture": "https://cdn.beeradvocate.com/im/beers/87343.jpg", "style": "American Amber / Red Ale", "name": "Revelry", "ba_ratings": "368", "city": "Illinois", "country": "United States", "producer": "Two Brothers Brewing Company", "ba_score": "90", "alcohol": " 9.50%\n\t\t"}
{"website": "newportstorm.com", "picture": "https://cdn.beeradvocate.com/im/beers/3153.jpg", "style": "American Amber / Red Ale", "name": "Newport Storm Hurricane Amber Ale", "ba_ratings": "333", "city": "Rhode Island", "country": "United States", "producer": "Coastal Extreme Brewing Co.", "ba_score": "75", "alcohol": " 5.20%\n\t\t"}
{"website": "samueladams.com", "picture": "https://cdn.beeradvocate.com/im/beers/183489.jpg", "style": "American Amber / Red Ale", "name": "Hoppy Red", "ba_ratings": "382", "city": "Massachusetts", "country": "United States", "producer": "Boston Beer Company (Samuel Adams)", "ba_score": "83", "alcohol": " 5.70%\n\t\t"}
{"website": "sierranevada.com", "picture": "https://cdn.beeradvocate.com/im/beers/88884.jpg", "style": "American Amber / Red Ale", "name": "Blood Shot - Beer Camp #95", "ba_ratings": "390", "city": "California", "country": "United States", "producer": "Sierra Nevada Brewing Co.", "ba_score": "86", "alcohol": " 8.50%\n\t\t"}
{"website": "odells.com", "picture": "https://cdn.beeradvocate.com/im/beers/737.jpg", "style": "American Amber / Red Ale", "name": "Odell Levity Amber Ale", "ba_ratings": "391", "city": "Colorado", "country": "United States", "producer": "Odell Brewing Company", "ba_score": "84", "alcohol": " 5.00%\n\t\t"}
{"website": "bluepointbrewing.com", "picture": "https://cdn.beeradvocate.com/im/beers/2819.jpg", "style": "American Amber / Red Ale", "name": "Blue Point Winter Ale", "ba_ratings": "400", "city": "New York", "country": "United States", "producer": "Blue Point Brewing Company", "ba_score": "80", "alcohol": " 7.00%\n\t\t"}
{"website": "lostcoast.com", "picture": "https://cdn.beeradvocate.com/im/beers/4923.jpg", "style": "American Amber / Red Ale", "name": "Alleycat Amber", "ba_ratings": "400", "city": "California", "country": "United States", "producer": "Lost Coast Brewery and Cafe", "ba_score": "82", "alcohol": " 5.50%\n\t\t"}
{"website": "deschutesbrewery.com", "picture": "https://cdn.beeradvocate.com/im/beers/40291.jpg", "style": "American Amber / Red Ale", "name": "Green Lakes Organic Ale", "ba_ratings": "351", "city": "Oregon", "country": "United States", "producer": "Deschutes Brewery", "ba_score": "85", "alcohol": " 5.20%\n\t\t"}
{"website": "macandjacks.com", "picture": "https://cdn.beeradvocate.com/im/placeholder-beer.jpg", "style": "American Amber / Red Ale", "name": "African Amber", "ba_ratings": "414", "city": "Washington", "country": "United States", "producer": "Mac and Jack's Brewery", "ba_score": "86", "alcohol": " 5.20%\n\t\t"}
{"website": "thirstydog.com", "picture": "https://cdn.beeradvocate.com/im/beers/27842.jpg", "style": "American Amber / Red Ale", "name": "Hoppus Maximus", "ba_ratings": "422", "city": "Ohio", "country": "United States", "producer": "Thirsty Dog Brewing Company", "ba_score": "83", "alcohol": " 5.90%\n\t\t"}
{"website": "hereticbrewing.com", "picture": "https://cdn.beeradvocate.com/im/beers/70945.jpg", "style": "American Amber / Red Ale", "name": "Evil Twin", "ba_ratings": "418", "city": "California", "country": "United States", "producer": "Heretic Brewing Company", "ba_score": "88", "alcohol": " 6.80%\n\t\t"}
{"website": "ninkasibrewing.com", "picture": "https://cdn.beeradvocate.com/im/beers/109613.jpg", "style": "American Amber / Red Ale", "name": "Dawn Of The Red I.R.A. Ale", "ba_ratings": "426", "city": "Oregon", "country": "United States", "producer": "Ninkasi Brewing Company", "ba_score": "87", "alcohol": " 7.00%\n\t\t"}
{"website": "eviltwin.dk", "picture": "https://cdn.beeradvocate.com/im/beers/77253.jpg", "style": "American Amber / Red Ale", "name": "Evil Twin Hop Flood", "ba_ratings": "418", "city": "New York", "country": "United States", "producer": "Evil Twin Brewing", "ba_score": "86", "alcohol": " 7.00%\n\t\t"}
{"website": "finchbeer.com", "picture": "https://cdn.beeradvocate.com/im/beers/83115.jpg", "style": "American Amber / Red Ale", "name": "Fascist Pig Ale", "ba_ratings": "431", "city": "Illinois", "country": "United States", "producer": "Finch's Beer Co.", "ba_score": "83", "alcohol": " 8.00%\n\t\t"}
{"website": "atlantabrewing.com", "picture": "https://cdn.beeradvocate.com/im/beers/55099.jpg", "style": "American Amber / Red Ale", "name": "Laughing Skull Amber Ale", "ba_ratings": "446", "city": "Georgia", "country": "United States", "producer": "Red Brick Brewing Company", "ba_score": "78", "alcohol": " 5.70%\n\t\t"}
{"website": "floridabeer.com", "picture": "https://cdn.beeradvocate.com/im/beers/2350.jpg", "style": "American Amber / Red Ale", "name": "Key West Sunset Ale", "ba_ratings": "426", "city": "Florida", "country": "United States", "producer": "Florida Beer Company", "ba_score": "72", "alcohol": " 4.80%\n\t\t"}
{"website": "flyingfish.com", "picture": "https://cdn.beeradvocate.com/im/beers/78192.jpg", "style": "American Amber / Red Ale", "name": "Red Fish India Red Ale", "ba_ratings": "435", "city": "New Jersey", "country": "United States", "producer": "Flying Fish Brewing Company", "ba_score": "84", "alcohol": " 7.00%\n\t\t"}
{"website": "breweryvivant.com", "picture": "https://cdn.beeradvocate.com/im/beers/66219.jpg", "style": "American Amber / Red Ale", "name": "Big Red Coq", "ba_ratings": "439", "city": "Michigan", "country": "United States", "producer": "Brewery Vivant", "ba_score": "87", "alcohol": " 6.50%\n\t\t"}
{"website": "widmer.com", "picture": "https://cdn.beeradvocate.com/im/beers/8917.jpg", "style": "American Amber / Red Ale", "name": "Drop Top Amber", "ba_ratings": "425", "city": "Oregon", "country": "United States", "producer": "Widmer Brothers Brewing Company", "ba_score": "77", "alcohol": " 5.00%\n\t\t"}
{"website": "darkhorsebrewery.com", "picture": "https://cdn.beeradvocate.com/im/beers/5387.jpg", "style": "American Amber / Red Ale", "name": "Dark Horse Amber Ale", "ba_ratings": "439", "city": "Michigan", "country": "United States", "producer": "Dark Horse Brewing Company", "ba_score": "80", "alcohol": " 5.50%\n\t\t"}
{"website": "fortcollinsbrewery.com", "picture": "https://cdn.beeradvocate.com/im/beers/66161.jpg", "style": "American Amber / Red Ale", "name": "Red Banshee Red Alt Ale", "ba_ratings": "407", "city": "Colorado", "country": "United States", "producer": "The Fort Collins Brewery", "ba_score": "79", "alcohol": " 5.30%\n\t\t"}
{"website": "deschutesbrewery.com", "picture": "https://cdn.beeradvocate.com/im/beers/6502.jpg", "style": "American Amber / Red Ale", "name": "Cinder Cone Red", "ba_ratings": "466", "city": "Oregon", "country": "United States", "producer": "Deschutes Brewery", "ba_score": "88", "alcohol": " 5.50%\n\t\t"}
{"website": "terrapinbeer.com", "picture": "https://cdn.beeradvocate.com/im/beers/45779.jpg", "style": "American Amber / Red Ale", "name": "Terrapin Oaked Big Hoppy Monster", "ba_ratings": "564", "city": "Georgia", "country": "United States", "producer": "Terrapin Beer Company", "ba_score": "87", "alcohol": " 10.30%\n\t\t"}
{"website": "newhollandbrew.com", "picture": "https://cdn.beeradvocate.com/im/beers/6343.jpg", "style": "American Amber / Red Ale", "name": "Sundog Amber Ale", "ba_ratings": "466", "city": "Michigan", "country": "United States", "producer": "New Holland Brewing Company", "ba_score": "81", "alcohol": " 5.25%\n\t\t"}
{"website": "localoptionbier.com", "picture": "https://cdn.beeradvocate.com/im/beers/76109.jpg", "style": "American Amber / Red Ale", "name": "Mourning Wood", "ba_ratings": "499", "city": "Illinois", "country": "United States", "producer": "Local Option", "ba_score": "86", "alcohol": " 7.30%\n\t\t"}
{"website": "grandtetonbrewing.com", "picture": "https://cdn.beeradvocate.com/im/beers/53266.jpg", "style": "American Amber / Red Ale", "name": "Pursuit Of Hoppiness", "ba_ratings": "497", "city": "Idaho", "country": "United States", "producer": "Grand Teton Brewing Co.", "ba_score": "89", "alcohol": " 8.50%\n\t\t"}
{"website": "samueladams.com", "picture": "https://cdn.beeradvocate.com/im/beers/75435.jpg", "style": "American Amber / Red Ale", "name": "Samuel Adams Mighty Oak Ale", "ba_ratings": "501", "city": "Massachusetts", "country": "United States", "producer": "Boston Beer Company (Samuel Adams)", "ba_score": "79", "alcohol": " 5.70%\n\t\t"}
{"website": "saintarnold.com", "picture": "https://cdn.beeradvocate.com/im/beers/1065.jpg", "style": "American Amber / Red Ale", "name": "Saint Arnold Amber Ale", "ba_ratings": "505", "city": "Texas", "country": "United States", "producer": "Saint Arnold Brewing Company", "ba_score": "81", "alcohol": " 5.50%\n\t\t"}
{"website": "bellsbeer.com", "picture": "https://cdn.beeradvocate.com/im/beers/48134.jpg", "style": "American Amber / Red Ale", "name": "Roundhouse IRA", "ba_ratings": "515", "city": "Michigan", "country": "United States", "producer": "Bell's Brewery, Inc.", "ba_score": "90", "alcohol": " 7.50%\n\t\t"}
{"website": "sierranevada.com", "picture": "https://cdn.beeradvocate.com/im/beers/82083.jpg", "style": "American Amber / Red Ale", "name": "Red-oric - Beer Camp #65 (Best Of Beer Camp: Imperial Red Ale)", "ba_ratings": "504", "city": "California", "country": "United States", "producer": "Sierra Nevada Brewing Co.", "ba_score": "85", "alcohol": " 8.00%\n\t\t"}
{"website": "madriverbrewing.com", "picture": "https://cdn.beeradvocate.com/im/beers/735.jpg", "style": "American Amber / Red Ale", "name": "Jamaica Red Ale", "ba_ratings": "503", "city": "California", "country": "United States", "producer": "Mad River Brewing Company", "ba_score": "86", "alcohol": " 6.50%\n\t\t"}
{"website": "redhook.com", "picture": "https://cdn.beeradvocate.com/im/beers/35061.jpg", "style": "American Amber / Red Ale", "name": "Redhook Copperhook", "ba_ratings": "505", "city": "New Hampshire", "country": "United States", "producer": "Redhook Ale Brewery", "ba_score": "76", "alcohol": " 5.80%\n\t\t"}
{"website": "coors.com", "picture": "https://cdn.beeradvocate.com/im/beers/77796.jpg", "style": "American Amber / Red Ale", "name": "Blue Moon Valencia Amber Ale", "ba_ratings": "473", "city": "Colorado", "country": "United States", "producer": "Coors Brewing Company", "ba_score": "71", "alcohol": " 5.90%\n\t\t"}
{"website": "newglarusbrewing.com", "picture": "https://cdn.beeradvocate.com/im/beers/3239.jpg", "style": "American Amber / Red Ale", "name": "Snowshoe Red Ale", "ba_ratings": "459", "city": "Wisconsin", "country": "United States", "producer": "New Glarus Brewing Company", "ba_score": "83", "alcohol": " 5.70%\n\t\t"}
{"website": "ninkasibrewing.com", "picture": "https://cdn.beeradvocate.com/im/beers/37381.jpg", "style": "American Amber / Red Ale", "name": "Believer", "ba_ratings": "520", "city": "Oregon", "country": "United States", "producer": "Ninkasi Brewing Company", "ba_score": "85", "alcohol": " 6.90%\n\t\t"}
{"website": "duckrabbitbrewery.com", "picture": "https://cdn.beeradvocate.com/im/beers/19976.jpg", "style": "American Amber / Red Ale", "name": "Duck-Rabbit Amber Ale", "ba_ratings": "524", "city": "North Carolina", "country": "United States", "producer": "The Duck-Rabbit Craft Brewery", "ba_score": "78", "alcohol": " 5.50%\n\t\t"}
{"website": "thebruery.com", "picture": "https://cdn.beeradvocate.com/im/beers/62063.jpg", "style": "American Amber / Red Ale", "name": "Loakal Red", "ba_ratings": "543", "city": "California", "country": "United States", "producer": "The Bruery", "ba_score": "89", "alcohol": " 6.90%\n\t\t"}
{"website": "mainebeercompany.com", "picture": "https://cdn.beeradvocate.com/im/beers/103142.jpg", "style": "American Amber / Red Ale", "name": "Red Wheelbarrow", "ba_ratings": "961", "city": "Maine", "country": "United States", "producer": "Maine Beer Company", "ba_score": "91", "alcohol": " 7.00%\n\t\t"}
{"website": "lakefrontbrewery.com", "picture": "https://cdn.beeradvocate.com/im/beers/56386.jpg", "style": "American Amber / Red Ale", "name": "Fixed Gear", "ba_ratings": "926", "city": "Wisconsin", "country": "United States", "producer": "Lakefront Brewery, Inc.", "ba_score": "85", "alcohol": " 6.80%\n\t\t"}
{"website": "ballastpoint.com", "picture": "https://cdn.beeradvocate.com/im/beers/7306.jpg", "style": "American Amber / Red Ale", "name": "Tongue Buckler - Imperial Red Ale", "ba_ratings": "938", "city": "California", "country": "United States", "producer": "Ballast Point Brewing Company", "ba_score": "87", "alcohol": " 10.00%\n\t\t"}
{"website": null, "picture": "https://cdn.beeradvocate.com/im/beers/631.jpg", "style": null, "name": "Red Tail Ale", "ba_ratings": "961", "city": "United States", "country": "mendobrew.com", "producer": "Mendocino Brewing Company", "ba_score": "79", "alcohol": "\n\t\t"}
{"website": "goodbeer.com", "picture": "https://cdn.beeradvocate.com/im/beers/1468.jpg", "style": "American Amber / Red Ale", "name": "Prohibition Ale", "ba_ratings": "966", "city": "California", "country": "United States", "producer": "Speakeasy Ales & Lagers", "ba_score": "86", "alcohol": " 6.10%\n\t\t"}
{"website": "anchorbrewing.com", "picture": "https://cdn.beeradvocate.com/im/beers/97721.jpg", "style": "American Amber / Red Ale", "name": "Anchor BigLeaf Maple Autumn Red", "ba_ratings": "976", "city": "California", "country": "United States", "producer": "Anchor Brewing Company", "ba_score": "82", "alcohol": " 6.00%\n\t\t"}
{"website": "brewdog.com", "picture": "https://cdn.beeradvocate.com/im/beers/55191.jpg", "style": "American Amber / Red Ale", "name": "5AM Saint", "ba_ratings": "836", "city": "Scotland", "country": "United Kingdom", "producer": "BrewDog", "ba_score": "86", "alcohol": " 5.00%\n\t\t"}
{"website": "alesmith.com", "picture": "https://cdn.beeradvocate.com/im/beers/47647.jpg", "style": "American Amber / Red Ale", "name": "Double Red India Pale Ale", "ba_ratings": "886", "city": "California", "country": "United States", "producer": "AleSmith Brewing Company", "ba_score": "91", "alcohol": " 8.50%\n\t\t"}
{"website": "stonebrewing.com", "picture": "https://cdn.beeradvocate.com/im/beers/199848.jpg", "style": "American Amber / Red Ale", "name": "Stone Pataskala Red X IPA", "ba_ratings": "1,018", "city": "California", "country": "United States", "producer": "Stone Brewing", "ba_score": "91", "alcohol": " 7.30%\n\t\t"}
{"website": "rogue.com", "picture": "https://cdn.beeradvocate.com/im/beers/1597.jpg", "style": "American Amber / Red Ale", "name": "St. Rogue Red", "ba_ratings": "1,050", "city": "Oregon", "country": "United States", "producer": "Rogue Ales", "ba_score": "85", "alcohol": " 5.10%\n\t\t"}
{"website": "fullsailbrewing.com", "picture": "https://cdn.beeradvocate.com/im/beers/213.jpg", "style": "American Amber / Red Ale", "name": "Full Sail Amber", "ba_ratings": "1,185", "city": "Oregon", "country": "United States", "producer": "Full Sail Brewery & Tasting Room & Pub", "ba_score": "85", "alcohol": " 6.00%\n\t\t"}
{"website": "sixpoint.com", "picture": "https://cdn.beeradvocate.com/im/beers/104466.jpg", "style": "American Amber / Red Ale", "name": "Global Warmer", "ba_ratings": "1,188", "city": "New York", "country": "United States", "producer": "Sixpoint Brewery", "ba_score": "88", "alcohol": " 7.00%\n\t\t"}
{"website": "ithacabeer.com", "picture": "https://cdn.beeradvocate.com/im/beers/18721.jpg", "style": "American Amber / Red Ale", "name": "CascaZilla", "ba_ratings": "1,227", "city": "New York", "country": "United States", "producer": "Ithaca Beer Company", "ba_score": "87", "alcohol": " 7.00%\n\t\t"}
{"website": "ballastpoint.com", "picture": "https://cdn.beeradvocate.com/im/beers/691.jpg", "style": "American Amber / Red Ale", "name": "California Amber", "ba_ratings": "1,431", "city": "California", "country": "United States", "producer": "Ballast Point Brewing Company", "ba_score": "86", "alcohol": " 5.50%\n\t\t"}
